/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Utilitarios.ConectaBD;
import gestordeobras.ClsPedidoCompras;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Gustavo
 */
public class JDialogMovPedidoCompras extends javax.swing.JDialog {

    private ClsPedidoCompras objPedidoCompras;
    private Date data = null;
    private String dataTexto;
    private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    private java.util.Date dataUtil = new java.util.Date();
    private String DataC;
    private String DataE;
    /**
     * Creates new form JDialogMovEstoqueEntrada
     */
    public JDialogMovPedidoCompras(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        
        objPedidoCompras = new ClsPedidoCompras();
        
        Connection c = ConectaBD.getconexao();
        String ConsultaSQL = "";
        ConsultaSQL = "SELECT i.Nome FROM insumo i";
        ResultSet rs;
        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();
            
            
            while(rs.next()) {
                
                jComboBoxInsumo.addItem(rs.getString("i.Nome"));
                
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }
        
        ConsultaSQL = "SELECT f.Nome FROM fornecedor f";
        
        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();
            
            
            while(rs.next()) {
                
                jComboBoxFornecedor.addItem(rs.getString("f.Nome"));
                
                
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxFornecedor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxInsumo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Quantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Preco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DataCompra = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        DataEntrega = new javax.swing.JFormattedTextField();
        Salvar = new javax.swing.JButton();
        SalvarVoltar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descricao = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movimento Pedido de Compra");

        jLabel1.setText("Fornecedor *");

        jLabel2.setText("Insumo *");

        jLabel3.setText("Quantidade *");

        Quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantidadeActionPerformed(evt);
            }
        });
        Quantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantidadeKeyTyped(evt);
            }
        });

        jLabel4.setText("Preço Unitário *");

        Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoActionPerformed(evt);
            }
        });
        Preco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecoKeyTyped(evt);
            }
        });

        jLabel5.setText("Data Compra *");

        try {
            DataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Data Entrega *");

        try {
            DataEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        SalvarVoltar.setText("Salvar e Voltar");
        SalvarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarVoltarActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        jLabel7.setText("Descrição");

        jScrollPane1.setViewportView(Descricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SalvarVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(Voltar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DataCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addGap(91, 91, 91)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBoxInsumo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(jComboBoxInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarVoltar)
                    .addComponent(Salvar)
                    .addComponent(Voltar))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(399, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarVoltarActionPerformed
        if(Quantidade.getText().equals("") || Preco.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campos com  asteriscos (*) são obrigatórios!!!");
        }else{
            
            int CodI, CodF;
            double Qtd, PU;
            String NomeI, NomeF;
            
            
            DataC = new String(DataCompra.getText());
            DataE = new String(DataEntrega.getText());
            format.setLenient(false);
            try {
                data = format.parse(DataC);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            java.sql.Date dataSqlC = new java.sql.Date(dataUtil.getTime());

            format.setLenient(false);
            try {
                data = format.parse(DataE);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            java.sql.Date dataSqlE = new java.sql.Date(dataUtil.getTime());
            
            NomeI = (String) jComboBoxInsumo.getSelectedItem();
            
            CodI = objPedidoCompras.PesquisaridInsumo(NomeI);
            
            NomeF = (String) jComboBoxFornecedor.getSelectedItem();
            
            CodF = objPedidoCompras.PesquisaridFornecedor(NomeF);
            
            Qtd = Double.parseDouble(Quantidade.getText());
            PU = Double.parseDouble(Preco.getText());
            
            objPedidoCompras.setQuantidade(Qtd);
            objPedidoCompras.setPrecoUnitario(PU);
            objPedidoCompras.setCodFornecedor(CodF);
            objPedidoCompras.setCodInsumo(CodI);
            objPedidoCompras.setDataCompra(dataSqlC);
            objPedidoCompras.setDataEntrega(dataSqlE);
            objPedidoCompras.setDescricao(Descricao.getText());
            
            if(objPedidoCompras.Salvar()){
                JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!!!");
                dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao salvar dados!!!");
            }
            
        }
    }//GEN-LAST:event_SalvarVoltarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoActionPerformed
        
    }//GEN-LAST:event_PrecoActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
       if(Quantidade.getText().equals("") || Preco.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campos com * são obrigatorios!!!");
        }else{
            int CodI, CodF;
            double Qtd, PU;
            String NomeI, NomeF;
            
            
            DataC = new String(DataCompra.getText());
            DataE = new String(DataEntrega.getText());
            format.setLenient(false);
            try {
                data = format.parse(DataC);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            java.sql.Date dataSqlC = new java.sql.Date(dataUtil.getTime());

            format.setLenient(false);
            try {
                data = format.parse(DataE);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            java.sql.Date dataSqlE = new java.sql.Date(dataUtil.getTime());
            
            NomeI = (String) jComboBoxInsumo.getSelectedItem();
            
            CodI = objPedidoCompras.PesquisaridInsumo(NomeI);
            
            NomeF = (String) jComboBoxFornecedor.getSelectedItem();
            
            CodF = objPedidoCompras.PesquisaridFornecedor(NomeF);
            
            Qtd = Double.parseDouble(Quantidade.getText());
            PU = Double.parseDouble(Preco.getText());
            
            objPedidoCompras.setQuantidade(Qtd);
            objPedidoCompras.setPrecoUnitario(PU);
            objPedidoCompras.setCodFornecedor(CodF);
            objPedidoCompras.setCodInsumo(CodI);
            objPedidoCompras.setDataCompra(dataSqlC);
            objPedidoCompras.setDataEntrega(dataSqlE);
            objPedidoCompras.setDescricao(Descricao.getText());
            
            if(objPedidoCompras.Salvar()){
                JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!!!");
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao salvar dados!!!");
            }
            
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void QuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantidadeActionPerformed

    private void QuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantidadeKeyTyped
String caracteres="0987654321.";// lista de caracters que não devem ser aceitos
if(!caracteres.contains(evt.getKeyChar()+"")){// se o caracter que gerou o evento estiver não estiver na lista
evt.consume();//aciona esse propriedade para eliminar a ação do evento





}


        // TODO add your handling code here:
    }//GEN-LAST:event_QuantidadeKeyTyped

    private void PrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecoKeyTyped
String caracteres="0987654321.";// lista de caracters que não devem ser aceitos
if(!caracteres.contains(evt.getKeyChar()+"")){// se o caracter que gerou o evento estiver não estiver na lista
evt.consume();//aciona esse propriedade para eliminar a ação do evento





}


        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogMovPedidoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogMovPedidoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogMovPedidoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogMovPedidoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogMovPedidoCompras dialog = new JDialogMovPedidoCompras(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField DataCompra;
    private javax.swing.JFormattedTextField DataEntrega;
    private javax.swing.JTextPane Descricao;
    private javax.swing.JTextField Preco;
    private javax.swing.JTextField Quantidade;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton SalvarVoltar;
    private javax.swing.JButton Voltar;
    private javax.swing.JComboBox<String> jComboBoxFornecedor;
    private javax.swing.JComboBox<String> jComboBoxInsumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
}
