/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Utilitarios.ConectaBD;
import gestordeobras.ClsObra;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class JDialogObra extends javax.swing.JDialog {

    private ClsObra objObra;
    
    private String Nome;
    
    /**
     * Creates new form JDialogObra
     */
    public JDialogObra(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        objObra = new ClsObra();
        
        objObra.carregaTabela(jTableObra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Novo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableObra = new javax.swing.JTable();
        Buscar = new javax.swing.JButton();
        BuscarNome = new javax.swing.JTextField();
        Excluir = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Obra");

        Novo.setText("Novo");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });

        jTableObra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cliente", "Descrição", "Data Término"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableObra);

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Voltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Novo)
                    .addComponent(Buscar)
                    .addComponent(BuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Excluir)
                    .addComponent(Alterar)
                    .addComponent(Voltar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(660, 405));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        JDialogCadObra frmDialog2 = new JDialogCadObra(new javax.swing.JDialog(), true);
        frmDialog2.setVisible(true);
        objObra.carregaTabela(jTableObra);
    }//GEN-LAST:event_NovoActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
         if (jTableObra.getSelectedRow() != -1) {
            Nome = jTableObra.getValueAt(jTableObra.getSelectedRow(), 0).toString();
            int CodObra;

            CodObra = objObra.PesquisarNome(Nome);

            if (objObra.Excluir(Nome)) {
                objObra.carregaTabela(jTableObra);
            } else {
                int opcao = JOptionPane.showConfirmDialog(null, Nome + " possui informações associadas a ele! Deseja"
                        + " apagar tudo?\nEsta operação não podera ser desfeita!", "Excluir Cliente", JOptionPane.YES_NO_OPTION);

                if (opcao == 0) {
                    Connection c = ConectaBD.getconexao();

                    String ConsultaSQL = "";
                    ConsultaSQL = "SELECT r.idRDOObra, r.obra_idobra, o.idobra FROM rdoobra r,obra o"
                            + " WHERE r.obra_idobra = o.idobra and o.idobra = ? ";
                    ResultSet rs;
                    try {
                        PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
                        Query1.setInt(1, CodObra);
                        rs = Query1.executeQuery();
                        while (rs.next()) {// se quisesse mais de uma colocar um while
                            if (rs.getInt("o.idobra") == CodObra) {

                                objObra.ExcluirMaodeObraRDO(rs.getInt("r.idRDOObra"));

                            }

                        }
                    } catch (java.sql.SQLException e) {
                        System.out.println(e.getMessage());

                    }

                    ConsultaSQL = "SELECT r.idRDOObra, r.obra_idobra, o.idobra FROM rdoobragrupo r, obra o"
                            + " WHERE r.obra_idobra = o.idobra and o.idobra = ?";
                    try {
                        PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
                        Query1.setInt(1, CodObra);
                        rs = Query1.executeQuery();
                        while (rs.next()) {// se quisesse mais de uma colocar um while
                            if (rs.getInt("o.idobra") == CodObra) {

                                objObra.ExcluirFuncionariosRDO(rs.getInt("r.idRDOObra"));

                            }

                        }
                    } catch (java.sql.SQLException e) {
                        System.out.println(e.getMessage());

                    }

                    objObra.ExcluirRDOObra(CodObra);
                    objObra.ExcluirRDOGrupo(CodObra);
                    objObra.Excluir(Nome);
                    objObra.carregaTabela(jTableObra);

                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma linha foi selecione uma linha ou existe RDOGrupo ou RDOGerais Relacionados!!!");
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        objObra.carregaTabelaBusca(jTableObra, BuscarNome.getText());
    }//GEN-LAST:event_BuscarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        if(jTableObra.getSelectedRow() != -1){
            this.Nome = jTableObra.getValueAt(jTableObra.getSelectedRow(), 0).toString();
            
            
            JDialogCadObra frmDialog2 = new JDialogCadObra(new javax.swing.JDialog(), true);
            frmDialog2.Alterar(Nome);
            frmDialog2.setVisible(true);
            objObra.carregaTabela(jTableObra);
            
        }else{
            JOptionPane.showMessageDialog(this,"Selecione uma linha!!!");
        }
    }//GEN-LAST:event_AlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogObra dialog = new JDialogObra(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField BuscarNome;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Novo;
    private javax.swing.JButton Voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableObra;
    // End of variables declaration//GEN-END:variables

     /**
     * @return the Nome
     */
    public String getNome() {
        return Nome;
    }

    /**
     * @param Nome the Nome to set
     */
    public void setNome(String Nome) {
        this.Nome = Nome;
    }

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
    
}

