/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Utilitarios.ConectaBD;
import gestordeobras.ClsEstoque;
import gestordeobras.ClsPedidoCompras;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Gustavo
 */
public class JDialogEstoquePedidos extends javax.swing.JDialog {

    private ClsEstoque objEstoque;
    private ClsPedidoCompras objPC;
    private String opcao;
    private String NomeI;
    private String NomeF;
    private Date data = null;
    private String DataI;
    private String DataF;
    private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    private java.util.Date dataUtil = new java.util.Date();
    private java.sql.Date dataSqlI;
    private java.sql.Date dataSqlF;
    /**
     * Creates new form JDialogEstoquePedidos
     */
    public JDialogEstoquePedidos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        objEstoque = new ClsEstoque();
        
        objPC = new ClsPedidoCompras();
        objEstoque.carregaTabelaPedidos(jTablePedidos);
        
        jComboBoxFornecedor.addItem("Todos");
        
        Connection c = ConectaBD.getconexao();
        String ConsultaSQL = "";
        ConsultaSQL = "SELECT Nome FROM fornecedor";
        ResultSet rs;
        
        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();
            
            
            while(rs.next()) {// se quisesse mais de uma colocar um while
                
                jComboBoxFornecedor.addItem(rs.getString("Nome"));
                
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }
        
        jComboBoxInsumo.addItem("Todos");
        
        ConsultaSQL = "SELECT Nome FROM insumo";
        
        
        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();
            
            
            while(rs.next()) {// se quisesse mais de uma colocar um while
                
                jComboBoxInsumo.addItem(rs.getString("Nome"));
                
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }
        
        jComboBoxInsumo.setEnabled(false);
        jComboBoxFornecedor.setEnabled(false);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcaoBuscar = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        GerarPDF = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jComboBoxFornecedor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        DataInicio = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        DataFim = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxInsumo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonFornecedor = new javax.swing.JRadioButton();
        jRadioButtonInsumo = new javax.swing.JRadioButton();
        jRadioButtonFornecedorDatas = new javax.swing.JRadioButton();
        jRadioButtonInsumoDatas = new javax.swing.JRadioButton();
        jRadioButtonDatas = new javax.swing.JRadioButton();
        jRadioButtonTodos = new javax.swing.JRadioButton();
        jRadioButtonTudo = new javax.swing.JRadioButton();
        jRadioButtonFornecedorInsumo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedidos de Compra");

        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fornecedor", "Descrição Insumo", "Data Compra", "Unidade", "Valor Unitário", "Quantidade", "Total", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePedidos);

        GerarPDF.setText("Gerar PDF");
        GerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarPDFActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Início:");

        try {
            DataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Data Fim:");

        try {
            DataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Fornecedor");

        jLabel4.setText("Insumo");

        jLabel5.setText("Opção Busca");

        OpcaoBuscar.add(jRadioButtonFornecedor);
        jRadioButtonFornecedor.setText("Fornecedor");
        jRadioButtonFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFornecedorMouseClicked(evt);
            }
        });

        OpcaoBuscar.add(jRadioButtonInsumo);
        jRadioButtonInsumo.setText("Insumo");
        jRadioButtonInsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonInsumoMouseClicked(evt);
            }
        });

        OpcaoBuscar.add(jRadioButtonFornecedorDatas);
        jRadioButtonFornecedorDatas.setText("Fornecedor e Datas");
        jRadioButtonFornecedorDatas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFornecedorDatasMouseClicked(evt);
            }
        });

        OpcaoBuscar.add(jRadioButtonInsumoDatas);
        jRadioButtonInsumoDatas.setText("Insumo e Datas");
        jRadioButtonInsumoDatas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonInsumoDatasMouseClicked(evt);
            }
        });

        OpcaoBuscar.add(jRadioButtonDatas);
        jRadioButtonDatas.setText("Datas");
        jRadioButtonDatas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonDatasMouseClicked(evt);
            }
        });

        OpcaoBuscar.add(jRadioButtonTodos);
        jRadioButtonTodos.setText("Todos os campos");
        jRadioButtonTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonTodosMouseClicked(evt);
            }
        });

        OpcaoBuscar.add(jRadioButtonTudo);
        jRadioButtonTudo.setSelected(true);
        jRadioButtonTudo.setText("Tudo");
        jRadioButtonTudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonTudoMouseClicked(evt);
            }
        });

        OpcaoBuscar.add(jRadioButtonFornecedorInsumo);
        jRadioButtonFornecedorInsumo.setText("Fornecedor e Insumo");
        jRadioButtonFornecedorInsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFornecedorInsumoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GerarPDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Voltar))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonTudo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonInsumo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonFornecedorInsumo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonFornecedorDatas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonInsumoDatas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonDatas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonTodos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(DataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButtonTudo)
                    .addComponent(jRadioButtonFornecedor)
                    .addComponent(jRadioButtonInsumo)
                    .addComponent(jRadioButtonFornecedorInsumo)
                    .addComponent(jRadioButtonFornecedorDatas)
                    .addComponent(jRadioButtonInsumoDatas)
                    .addComponent(jRadioButtonDatas)
                    .addComponent(jRadioButtonTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GerarPDF)
                    .addComponent(Voltar))
                .addGap(19, 19, 19))
        );

        setSize(new java.awt.Dimension(818, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarPDFActionPerformed
        
        
        
        MessageFormat header = new MessageFormat("INSTITUTO DE CIÊNCIAS AGRÁRIAS DA UFMG (PEDIDOS DE COMPRA):");
        MessageFormat footer = new MessageFormat("Pagina{0,number,integer}");

        try {
            jTablePedidos.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (Exception e) {
            System.err.format("Erro ao gerar pdf!!!", e.getMessage());
        }
        
        
    }//GEN-LAST:event_GerarPDFActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
      
        NomeF = (String) jComboBoxFornecedor.getSelectedItem();
        NomeI = (String) jComboBoxInsumo.getSelectedItem();
        
        DataI = new String(DataInicio.getText());
        DataF = new String(DataFim.getText());
        if(DataI.equals("  /  /    ")){
                
        }else{
        
            format.setLenient(false);
            try {
                data = format.parse(DataI);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            dataSqlI = new java.sql.Date(dataUtil.getTime());
        }
        
        if(DataF.equals("  /  /    ")){
                
        }else{
            format.setLenient(false);
            try {
                data = format.parse(DataF);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            dataSqlF = new java.sql.Date(dataUtil.getTime());  
        }
                  

        if(jRadioButtonTudo.isSelected()){
            
            objEstoque.carregaTabelaPedidos(jTablePedidos);
            
        }
        if(jRadioButtonFornecedor.isSelected()){
            if(NomeF.equals("Todos")){
                objEstoque.carregaTabelaPedidos(jTablePedidos);
            }else{
                objEstoque.carregaTabelaBuscaF(jTablePedidos, NomeF);
            }
        }
        if(jRadioButtonFornecedorDatas.isSelected()){
            
                    
            if(NomeF.equals("Todos")){    
                NomeF = (String) jComboBoxFornecedor.getSelectedItem();
        NomeI = (String) jComboBoxInsumo.getSelectedItem();
        
        DataI = new String(DataInicio.getText());
        DataF = new String(DataFim.getText());
        format.setLenient(false);
            try {
                data = format.parse(DataI);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            dataSqlI = new java.sql.Date(dataUtil.getTime());

            format.setLenient(false);
            try {
                data = format.parse(DataF);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            java.sql.Date dataSqlF = new java.sql.Date(dataUtil.getTime());  
                objEstoque.carregaTabelaBuscaFDIDF(jTablePedidos, dataSqlI, dataSqlF);
                
            }else{
                objEstoque.carregaTabelaBuscaFAll(jTablePedidos, NomeF, dataSqlI, dataSqlF);
            }
            
            
        }
        if(jRadioButtonDatas.isSelected() ){
            if(DataInicio.equals("  /  /    ")){
                JOptionPane.showMessageDialog(this, "Informe a Data Inicio!!!");
            }
            else if(DataFim.equals("  /  /    ")){
                JOptionPane.showMessageDialog(this, "Informe a Data Fim!!!");
            }else {
                objEstoque.carregaTabelaBuscaFDIDF(jTablePedidos, dataSqlI, dataSqlF);
            }
            
            
        }
        if(jRadioButtonInsumo.isSelected()){
            if(NomeI.equals("Todos")){
                objEstoque.carregaTabelaPedidos(jTablePedidos);
            }else{
                objEstoque.carregaTabelaBuscaI(jTablePedidos, NomeI);
            }
            
            
        }
        if(jRadioButtonTodos.isSelected()){
            if(NomeI.equals("Todos") && !"Todos".equals(NomeF)){
                objEstoque.carregaTabelaBuscaFAll(jTablePedidos, NomeF, dataSqlI, dataSqlF);
            }else if(NomeF.equals("Todos") && !"Todos".equals(NomeI)){
                objEstoque.carregaTabelaBuscaIAll(jTablePedidos, NomeI, dataSqlI, dataSqlF);
            }else if(NomeF.equals("Todos") && NomeI.equals("Todos")){
                objEstoque.carregaTabelaBuscaFDIDF(jTablePedidos, dataSqlI, dataSqlF);
            }else{
                objEstoque.carregaTabelaBuscaFIAll(jTablePedidos, NomeF, dataSqlI, dataSqlF, NomeI);
            }
            
            
            
        }
        if(jRadioButtonFornecedorInsumo.isSelected()){
            if(NomeI.equals("Todos")){
                objEstoque.carregaTabelaBuscaF(jTablePedidos, NomeF);
            }else if(NomeF.equals("Todos")){
                objEstoque.carregaTabelaBuscaI(jTablePedidos, NomeI);
            }else if(NomeF.equals("Todos") && NomeI.equals("Todos")){
                objEstoque.carregaTabelaPedidos(jTablePedidos);
            }else{
                objEstoque.carregaTabelaBuscaIF(jTablePedidos, NomeF, NomeI);
            }
            
            
        }
        if(jRadioButtonInsumoDatas.isSelected()){
            if(NomeI.equals("Todos")){
                objEstoque.carregaTabelaBuscaFDIDF(jTablePedidos, dataSqlI, dataSqlF);
            }else{
                objEstoque.carregaTabelaBuscaIAll(jTablePedidos, NomeI, dataSqlI, dataSqlF);
            }
            
        }
        
        
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jRadioButtonInsumoDatasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonInsumoDatasMouseClicked
        jComboBoxInsumo.setEnabled(true);
        jComboBoxFornecedor.setEnabled(false);
        DataFim.setEnabled(true);
        DataInicio.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonInsumoDatasMouseClicked

    private void jRadioButtonDatasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonDatasMouseClicked
        jComboBoxInsumo.setEnabled(false);
        jComboBoxFornecedor.setEnabled(false);
        DataFim.setEnabled(true);
        DataInicio.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonDatasMouseClicked

    private void jRadioButtonTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonTodosMouseClicked
        jComboBoxInsumo.setEnabled(true);
        jComboBoxFornecedor.setEnabled(true);
        DataFim.setEnabled(true);
        DataInicio.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonTodosMouseClicked

    private void jRadioButtonFornecedorDatasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFornecedorDatasMouseClicked
        jComboBoxInsumo.setEnabled(false);
        jComboBoxFornecedor.setEnabled(true);
        DataFim.setEnabled(true);
        DataInicio.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonFornecedorDatasMouseClicked

    private void jRadioButtonFornecedorInsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFornecedorInsumoMouseClicked
        jComboBoxInsumo.setEnabled(true);
        jComboBoxFornecedor.setEnabled(true);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonFornecedorInsumoMouseClicked

    private void jRadioButtonInsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonInsumoMouseClicked
        jComboBoxInsumo.setEnabled(true);
        jComboBoxFornecedor.setEnabled(false);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonInsumoMouseClicked

    private void jRadioButtonFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFornecedorMouseClicked
        jComboBoxInsumo.setEnabled(false);
        jComboBoxFornecedor.setEnabled(true);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonFornecedorMouseClicked

    private void jRadioButtonTudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonTudoMouseClicked
        jComboBoxInsumo.setEnabled(false);
        jComboBoxFornecedor.setEnabled(false);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonTudoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoquePedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoquePedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoquePedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoquePedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogEstoquePedidos dialog = new JDialogEstoquePedidos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField DataFim;
    private javax.swing.JFormattedTextField DataInicio;
    private javax.swing.JButton GerarPDF;
    private javax.swing.ButtonGroup OpcaoBuscar;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxFornecedor;
    private javax.swing.JComboBox<String> jComboBoxInsumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButtonDatas;
    private javax.swing.JRadioButton jRadioButtonFornecedor;
    private javax.swing.JRadioButton jRadioButtonFornecedorDatas;
    private javax.swing.JRadioButton jRadioButtonFornecedorInsumo;
    private javax.swing.JRadioButton jRadioButtonInsumo;
    private javax.swing.JRadioButton jRadioButtonInsumoDatas;
    private javax.swing.JRadioButton jRadioButtonTodos;
    private javax.swing.JRadioButton jRadioButtonTudo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePedidos;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
}
