/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Utilitarios.ConectaBD;
import gestordeobras.ClsEntradaInsumo;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class JDialogMovEstoqueEntrada extends javax.swing.JDialog {

    private ClsEntradaInsumo objEntradaInsumo;
    private Date data = null;
    private String dataTexto;
    private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    private java.util.Date dataUtil = new java.util.Date();
    private Connection c = ConectaBD.getconexao();
    private String ConsultaSQL = "";
    private ResultSet rs;

    /**
     * Creates new form JDialogMovEstoqueEntrada
     */
    public JDialogMovEstoqueEntrada(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        SetIcon();
        objEntradaInsumo = new ClsEntradaInsumo();

        jComboBoxGI.addItem(" ");
        jComboBoxGI.addItem("Todos");

        ConsultaSQL = "SELECT Nome FROM grupoinsumo ORDER BY Nome";
        ResultSet rs;
        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();

            while (rs.next()) {// se quisesse mais de uma colocar um while

                jComboBoxGI.addItem(rs.getString("Nome"));

            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }

        c = ConectaBD.getconexao();
        ConsultaSQL = "";
        ConsultaSQL = "SELECT Nome FROM insumo ORDER BY Nome";

        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();

            while (rs.next()) {// se quisesse mais de uma colocar um while

                Insumo.addItem(rs.getString("Nome"));

            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salvar = new javax.swing.JButton();
        SalvarVoltar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        DataEntrada = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        Insumo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Quantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxGI = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtfPesquisa = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movimento Estoque Entrada");

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        SalvarVoltar.setText("Salvar e Voltar");
        SalvarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarVoltarActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        try {
            DataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setText("Insumo *");

        jLabel2.setText("Quantidade *");

        Quantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantidadeKeyTyped(evt);
            }
        });

        jLabel3.setText("Data Entrada *");

        jLabel4.setText("Ex: 299.2");

        jLabel5.setText("Grupo Insumo");

        jComboBoxGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGIActionPerformed(evt);
            }
        });

        jLabel6.setText("Pesquisar");

        jtfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesquisaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGI, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Insumo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SalvarVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxGI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Insumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar)
                    .addComponent(SalvarVoltar)
                    .addComponent(Voltar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(422, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        if (Quantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campos com asterisco (*) são obrigatórios!!!");
        } else {
            Double Qtd, Qtd2, QtdResult;
            String Nome;
            int CodInsumo;

            Qtd = Double.parseDouble(Quantidade.getText());

            objEntradaInsumo.setQuantidade(Qtd);

            String dataTexto = new String(DataEntrada.getText());

            format.setLenient(false);
            try {
                data = format.parse(dataTexto);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            java.sql.Date dataSql = new java.sql.Date(dataUtil.getTime());

            objEntradaInsumo.setDataEntrada(dataSql);

            Nome = (String) Insumo.getSelectedItem();

            CodInsumo = objEntradaInsumo.PesquisarIdInsumo(Nome);

            objEntradaInsumo.setCodInsumo(CodInsumo);

            int opcao = JOptionPane.showConfirmDialog(this, "Insumo: " + Nome + "\nQuantidade: " + Qtd
                    + "\nData: " + dataTexto + "\nAs informações estão corretas?\n", "Movimento Estoque Entrada", JOptionPane.YES_NO_OPTION);

            if (opcao == 0) {
                if (objEntradaInsumo.Salvar()) {
                    JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!!!");
                    Qtd2 = objEntradaInsumo.PesquisarQtdInsumo(CodInsumo);
                    QtdResult = Qtd2 + Qtd;
                    objEntradaInsumo.AumentaQuantidadeInsumo(CodInsumo, QtdResult);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar dados!!!");
                }
            } else {

            }

        }

    }//GEN-LAST:event_SalvarActionPerformed

    private void SalvarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarVoltarActionPerformed
        if (Quantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campos com asteriscos (*) são obrigatórios!!!");
        } else {
            Double Qtd, Qtd2, QtdResult;
            String Nome;
            int CodInsumo;

            Qtd = Double.parseDouble(Quantidade.getText());

            objEntradaInsumo.setQuantidade(Qtd);

            String dataTexto = new String(DataEntrada.getText());

            format.setLenient(false);
            try {
                data = format.parse(dataTexto);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            java.sql.Date dataSql = new java.sql.Date(dataUtil.getTime());

            objEntradaInsumo.setDataEntrada(dataSql);

            Nome = (String) Insumo.getSelectedItem();

            CodInsumo = objEntradaInsumo.PesquisarIdInsumo(Nome);

            objEntradaInsumo.setCodInsumo(CodInsumo);

            int opcao = JOptionPane.showConfirmDialog(this, "Insumo: " + Nome + "\nQuantidade: " + Qtd
                    + "\nData: " + dataTexto + "\nAs informações estão corretas?\n", "Movimento Estoque Entrada", JOptionPane.YES_NO_OPTION);

            if (opcao == 0) {
                if (objEntradaInsumo.Salvar()) {
                    JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!!!");
                    Qtd2 = objEntradaInsumo.PesquisarQtdInsumo(CodInsumo);
                    QtdResult = Qtd2 + Qtd;
                    objEntradaInsumo.AumentaQuantidadeInsumo(CodInsumo, QtdResult);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar dados!!!");
                }
            } else {

            }

        }
    }//GEN-LAST:event_SalvarVoltarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void jComboBoxGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGIActionPerformed
        if (jComboBoxGI.getSelectedItem().equals("Todos")) {
            Insumo.removeAllItems();
            ConsultaSQL = "SELECT Nome FROM insumo ORDER BY Nome";

            try {
                PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
                rs = Query1.executeQuery();

                while (rs.next()) {// se quisesse mais de uma colocar um while

                    Insumo.addItem(rs.getString("Nome"));

                }
            } catch (java.sql.SQLException e) {
                System.out.println(e.getMessage());
            }
        } else {
            Insumo.removeAllItems();

            int CodGI;

            CodGI = objEntradaInsumo.PesquisaridGrupoInsumo((String) jComboBoxGI.getSelectedItem());

            Connection c = ConectaBD.getconexao();
            String ConsultaSQL = "";
            ConsultaSQL = "SELECT Nome FROM insumo WHERE GrupoInsumo_idGrupoInsumo = ? ORDER BY Nome";
            ResultSet rs;

            try {
                PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
                Query1.setInt(1, CodGI);
                rs = Query1.executeQuery();

                while (rs.next()) {// se quisesse mais de uma colocar um while

                    Insumo.addItem(rs.getString("Nome"));

                }
            } catch (java.sql.SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jComboBoxGIActionPerformed

    private void QuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantidadeKeyTyped
        String caracteres = "0987654321.";// lista de caracters que não devem ser aceitos
        if (!caracteres.contains(evt.getKeyChar() + "")) {// se o caracter que gerou o evento estiver não estiver na lista
            evt.consume();//aciona esse propriedade para eliminar a ação do evento

        }


    }//GEN-LAST:event_QuantidadeKeyTyped

    //Eugenio 03/01/2018
    private void jtfPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaKeyPressed
        String consultaSQL = "SELECT Nome FROM insumo WHERE Nome LIKE ? ORDER BY Nome";
        PreparedStatement query;
        ResultSet rs;
        String pesquisa = jtfPesquisa.getText();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Insumo.removeAllItems();

            try {
                query = c.prepareStatement(consultaSQL);
                query.setString(1, "%" + pesquisa + "%");
                rs = query.executeQuery();

                while (rs.next()) {
                    Insumo.addItem(rs.getString("Nome"));
                }

            } catch (java.sql.SQLException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jtfPesquisaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogMovEstoqueEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogMovEstoqueEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogMovEstoqueEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogMovEstoqueEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogMovEstoqueEntrada dialog = new JDialogMovEstoqueEntrada(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField DataEntrada;
    private javax.swing.JComboBox<String> Insumo;
    private javax.swing.JTextField Quantidade;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton SalvarVoltar;
    private javax.swing.JButton Voltar;
    private javax.swing.JComboBox<String> jComboBoxGI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jtfPesquisa;
    // End of variables declaration//GEN-END:variables

    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
}
