/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Utilitarios.ConectaBD;
import gestordeobras.ClsEstoqueEntrada;
import gestordeobras.ClsEstoqueSaida;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Gustavo
 */
public class JDialogEstoqueEntSaida extends javax.swing.JDialog {
    private ClsEstoqueSaida objEstoque2;
    private ClsEstoqueEntrada objEstoque;
    private String NomeI;
    private String NomeGI;
    private Date data = null;
    private String DataI;
    private String DataF;
    private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    private java.util.Date dataUtil = new java.util.Date();
    private java.sql.Date dataSqlI;
    private java.sql.Date dataSqlF;
    /**
     * Creates new form JDialogEstoqueEntrada
     */
    public JDialogEstoqueEntSaida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        objEstoque = new ClsEstoqueEntrada();
        objEstoque2 = new ClsEstoqueSaida();
        
        objEstoque.carregaTabela(jTableEstoqueEntrada);
        objEstoque2.carregaTabela(jTableEstoqueSaida);
        
        jComboBoxInsumo.addItem("Todos");
        
        
       
        
        
        Connection c = ConectaBD.getconexao();
        String ConsultaSQL = "";
        ConsultaSQL = "SELECT Nome FROM insumo";
        ResultSet rs;
        
        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();
            
            
            while(rs.next()) {// se quisesse mais de uma colocar um while
                
                jComboBoxInsumo.addItem(rs.getString("Nome"));
                
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }
        
        jComboBoxGI.addItem("Todos");
        
        ConsultaSQL = "SELECT Nome FROM grupoinsumo";
        
        
        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();
            
            
            while(rs.next()) {// se quisesse mais de uma colocar um while
                
                jComboBoxGI.addItem(rs.getString("Nome"));
                
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }
        
        jComboBoxGI.setEnabled(false);
        jComboBoxInsumo.setEnabled(false);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoOpcao = new javax.swing.ButtonGroup();
        Buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstoqueEntrada = new javax.swing.JTable();
        Voltar = new javax.swing.JButton();
        GerarPDF = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxInsumo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxGI = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        DataInicio = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        DataFim = new javax.swing.JFormattedTextField();
        jRadioButtonInsumo = new javax.swing.JRadioButton();
        jRadioButtonGI = new javax.swing.JRadioButton();
        jRadioButtonIData = new javax.swing.JRadioButton();
        jRadioButtonGIData = new javax.swing.JRadioButton();
        jRadioButtonData = new javax.swing.JRadioButton();
        jRadioButtonTudo = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEstoqueSaida = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque Entrada");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Opções");

        jTableEstoqueEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Insumo", "Grupo Insumo", "Data Entrada", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEstoqueEntrada);

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        GerarPDF.setText("GerarPDF");
        GerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarPDFActionPerformed(evt);
            }
        });

        jLabel2.setText("Insumo");

        jLabel3.setText("Grupo Insumo");

        jLabel4.setText("Data Início:");

        try {
            DataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Data Fim:");

        try {
            DataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        GrupoOpcao.add(jRadioButtonInsumo);
        jRadioButtonInsumo.setText("Insumo");
        jRadioButtonInsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonInsumoMouseClicked(evt);
            }
        });

        GrupoOpcao.add(jRadioButtonGI);
        jRadioButtonGI.setText("Grupo Insumo");
        jRadioButtonGI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonGIMouseClicked(evt);
            }
        });

        GrupoOpcao.add(jRadioButtonIData);
        jRadioButtonIData.setText("Insumo e Data");
        jRadioButtonIData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonIDataMouseClicked(evt);
            }
        });

        GrupoOpcao.add(jRadioButtonGIData);
        jRadioButtonGIData.setText("Grupo Insumo e Data");
        jRadioButtonGIData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonGIDataMouseClicked(evt);
            }
        });

        GrupoOpcao.add(jRadioButtonData);
        jRadioButtonData.setText("Data");
        jRadioButtonData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonDataMouseClicked(evt);
            }
        });

        GrupoOpcao.add(jRadioButtonTudo);
        jRadioButtonTudo.setSelected(true);
        jRadioButtonTudo.setText("Exibir Tudo");
        jRadioButtonTudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonTudoMouseClicked(evt);
            }
        });

        jTableEstoqueSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Insumo", "Grupo Insumo", "Data Saida", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableEstoqueSaida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGI, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonIData)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonGIData)
                                .addGap(24, 24, 24)
                                .addComponent(jRadioButtonTudo)
                                .addGap(24, 24, 24)
                                .addComponent(jRadioButtonInsumo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonGI)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buscar)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GerarPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Voltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(DataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxGI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonData)
                        .addComponent(Buscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jRadioButtonIData)
                        .addComponent(jRadioButtonGIData)
                        .addComponent(jRadioButtonTudo)
                        .addComponent(jRadioButtonInsumo)
                        .addComponent(jRadioButtonGI)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(GerarPDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Voltar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(827, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonTudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonTudoMouseClicked
        jComboBoxGI.setEnabled(false);
        jComboBoxInsumo.setEnabled(false);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
        objEstoque.carregaTabela(jTableEstoqueEntrada);
        objEstoque2.carregaTabela(jTableEstoqueSaida);
    }//GEN-LAST:event_jRadioButtonTudoMouseClicked

    private void jRadioButtonInsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonInsumoMouseClicked
        jComboBoxGI.setEnabled(false);
        jComboBoxInsumo.setEnabled(true);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonInsumoMouseClicked

    private void jRadioButtonGIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonGIMouseClicked
        jComboBoxGI.setEnabled(true);
        jComboBoxInsumo.setEnabled(false);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonGIMouseClicked

    private void jRadioButtonIDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonIDataMouseClicked
        jComboBoxGI.setEnabled(false);
        jComboBoxInsumo.setEnabled(true);
        DataFim.setEnabled(true);
        DataInicio.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonIDataMouseClicked

    private void jRadioButtonGIDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonGIDataMouseClicked
        jComboBoxGI.setEnabled(true);
        jComboBoxInsumo.setEnabled(false);
        DataFim.setEnabled(true);
        DataInicio.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonGIDataMouseClicked

    private void jRadioButtonDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonDataMouseClicked
        jComboBoxGI.setEnabled(false);
        jComboBoxInsumo.setEnabled(false);
        DataFim.setEnabled(true);
        DataInicio.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonDataMouseClicked

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        NomeGI = (String) jComboBoxGI.getSelectedItem();
        NomeI = (String) jComboBoxInsumo.getSelectedItem();
        
        DataI = new String(DataInicio.getText());
        DataF = new String(DataFim.getText());
        if(DataI.equals("  /  /    ")){
                
        }else{
        
            format.setLenient(false);
            try {
                data = format.parse(DataI);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            dataSqlI = new java.sql.Date(dataUtil.getTime());
        }
        
        if(DataF.equals("  /  /    ")){
                
        }else{
            format.setLenient(false);
            try {
                data = format.parse(DataF);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            dataSqlF = new java.sql.Date(dataUtil.getTime());  
        }
            
            
            if(jRadioButtonInsumo.isSelected()){
                if(NomeI.equals("Todos")){
                    objEstoque.carregaTabela(jTableEstoqueEntrada);
                    objEstoque2.carregaTabela(jTableEstoqueSaida);
                }else{
                    objEstoque.carregaBuscaI(jTableEstoqueEntrada, NomeI);
                    objEstoque2.carregaBuscaI(jTableEstoqueSaida, NomeI);
                }
            }
            
            if(jRadioButtonGI.isSelected()){
                if(NomeGI.equals("Todos")){
                    objEstoque.carregaTabela(jTableEstoqueEntrada);
                      objEstoque2.carregaTabela(jTableEstoqueSaida);
                }else{
                    objEstoque.carregaBuscaGI(jTableEstoqueEntrada, NomeGI);
                    objEstoque2.carregaBuscaGI(jTableEstoqueSaida, NomeGI);
                }
            }
            
            if(jRadioButtonIData.isSelected()){
                if(NomeI.equals("Todos")){
                    objEstoque.carregaBuscaData(jTableEstoqueEntrada, dataSqlI, dataSqlF);
               objEstoque2.carregaBuscaData(jTableEstoqueSaida, dataSqlI, dataSqlF); }else{
                    objEstoque.carregaBuscaIData(jTableEstoqueEntrada, NomeI, dataSqlI, dataSqlF);
                objEstoque2.carregaBuscaIData(jTableEstoqueSaida, NomeI, dataSqlI, dataSqlF);}
            }
            
            if(jRadioButtonGIData.isSelected()){
                if(NomeGI.equals("Todos")){
                    objEstoque.carregaBuscaData(jTableEstoqueEntrada, dataSqlI, dataSqlF);
                                objEstoque2.carregaBuscaData(jTableEstoqueSaida, dataSqlI, dataSqlF);
;}else{
                    objEstoque.carregaBuscaGIData(jTableEstoqueEntrada, NomeGI, dataSqlI, dataSqlF);
                               objEstoque2.carregaBuscaIData(jTableEstoqueSaida, NomeI, dataSqlI, dataSqlF);
 }
            }
            
            if(jRadioButtonData.isSelected()){
                if(DataInicio.equals("  /  /    ")){
                    JOptionPane.showMessageDialog(this, "Informe a Data Inicio!!!");
                }
                else if(DataFim.equals("  /  /    ")){
                    JOptionPane.showMessageDialog(this, "Informe a Data Fim!!!");
                }else {
                    objEstoque.carregaBuscaData(jTableEstoqueEntrada, dataSqlI, dataSqlF);
                      objEstoque2.carregaBuscaData(jTableEstoqueSaida, dataSqlI, dataSqlF);
                }
            }
            
    }//GEN-LAST:event_BuscarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void GerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarPDFActionPerformed
        MessageFormat header = new MessageFormat("MOVIMENTAÇÃO - ENTRADA:");
        MessageFormat footer = new MessageFormat("Pagina{0,number,integer}");
        MessageFormat header1 = new MessageFormat("MOVIMENTAÇÃO - SAÍDA:");
        
        try {
            jTableEstoqueEntrada.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            jTableEstoqueSaida.print(JTable.PrintMode.FIT_WIDTH, header1, footer);
        } catch (Exception e) {
            System.err.format("Erro ao gerar pdf!!!", e.getMessage());
            
        }
    }//GEN-LAST:event_GerarPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoqueEntSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoqueEntSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoqueEntSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoqueEntSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogEstoqueEntSaida dialog = new JDialogEstoqueEntSaida(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JFormattedTextField DataFim;
    private javax.swing.JFormattedTextField DataInicio;
    private javax.swing.JButton GerarPDF;
    private javax.swing.ButtonGroup GrupoOpcao;
    private javax.swing.JButton Voltar;
    private javax.swing.JComboBox<String> jComboBoxGI;
    private javax.swing.JComboBox<String> jComboBoxInsumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButtonData;
    private javax.swing.JRadioButton jRadioButtonGI;
    private javax.swing.JRadioButton jRadioButtonGIData;
    private javax.swing.JRadioButton jRadioButtonIData;
    private javax.swing.JRadioButton jRadioButtonInsumo;
    private javax.swing.JRadioButton jRadioButtonTudo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEstoqueEntrada;
    private javax.swing.JTable jTableEstoqueSaida;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
}
