/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Utilitarios.ConectaBD;
import gestordeobras.ClsGrupoInsumo;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class JDialogGrupoInsumo extends javax.swing.JDialog {

    private ClsGrupoInsumo objGrupoInsumo;
    private String Nome1;
    private Connection c = ConectaBD.getconexao();
    private String ConsultaSQL = "";
    private ResultSet rs;

    /**
     * Creates new form JDialogGrupoInsumo
     */
    public JDialogGrupoInsumo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        objGrupoInsumo = new ClsGrupoInsumo();
        objGrupoInsumo.carregaTabela(jTableGInsumo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Novo = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        BuscarNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Sigla = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGInsumo = new javax.swing.JTable();
        Excluir = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        Pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Grupo Insumo");

        Novo.setText("Novo");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        BuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome *");

        jLabel2.setText("Sigla *");

        jTableGInsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sigla"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableGInsumo);

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Voltar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(Sigla))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Sigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Novo)
                    .addComponent(Buscar)
                    .addComponent(BuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Excluir)
                    .addComponent(Voltar)
                    .addComponent(Alterar)
                    .addComponent(Pesquisar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(423, 305));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarNomeActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        if (Nome.getText().equals("") || Sigla.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campos com * são obrigatorios!!!");
        } else {
            objGrupoInsumo.setNome(Nome.getText());
            objGrupoInsumo.setSigla(Sigla.getText());

            if (objGrupoInsumo.PesquisarNome(Nome.getText()) == -1) {
                if (objGrupoInsumo.Salvar()) {
                    JOptionPane.showMessageDialog(this, "Dados gravados com sucesso!!!");
                    objGrupoInsumo.carregaTabela(jTableGInsumo);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar dados!!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nome de Grupo Insumo já existente favor mudar!!!");
            }
        }
    }//GEN-LAST:event_NovoActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        objGrupoInsumo.carregaTabelaBusca(jTableGInsumo, BuscarNome.getText());
    }//GEN-LAST:event_BuscarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        String Nome;
        int Codigo;

        if (jTableGInsumo.getSelectedRow() != -1) {
            Nome = jTableGInsumo.getValueAt(jTableGInsumo.getSelectedRow(), 0).toString();
            Codigo = objGrupoInsumo.Pesquisarid(Nome);
            if (Codigo == -1) {
                objGrupoInsumo.Excluir(Nome);
                objGrupoInsumo.carregaTabela(jTableGInsumo);

            } else {
                int opcao = JOptionPane.showConfirmDialog(null, Nome + " possui informações associadas a ele! Deseja"
                        + " apagar tudo?\nEsta operação não podera ser desfeita!", "Excluir Grupo Insumo", JOptionPane.YES_NO_OPTION);

                if (opcao == 0) {

                    ConsultaSQL = "SELECT i.idInsumo FROM grupoinsumo g, insumo i WHERE g.Nome = ? and g.idGrupoInsumo = i.GrupoInsumo_idGrupoInsumo";

                    try {
                        PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
                        Query1.setString(1, Nome);
                        rs = Query1.executeQuery();

                        while (rs.next()) {// se quisesse mais de uma colocar um while
                            objGrupoInsumo.ExcluirEntrada(rs.getInt("i.idInsumo"));
                            objGrupoInsumo.ExcluirSaida(rs.getInt("i.idInsumo"));
                            objGrupoInsumo.ExcluirPedido(rs.getInt("i.idInsumo"));
                            objGrupoInsumo.ExcluirInsumo(rs.getInt("i.idInsumo"));

                        }
                    } catch (java.sql.SQLException e) {
                        System.out.println(e.getMessage());
                    }

                    objGrupoInsumo.Excluir(Nome);
                    objGrupoInsumo.carregaTabela(jTableGInsumo);
                } else {

                }
            }
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed

        int Codigo;

        if (Nome.getText().equals("") || Sigla.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Favor pesquisar antes!!!");
        } else {
            objGrupoInsumo.setNome(Nome.getText());
            objGrupoInsumo.setSigla(Sigla.getText());

            if (objGrupoInsumo.PesquisarNome(Nome.getText()) == -1) {
                if (objGrupoInsumo.Alterar(Nome1)) {
                    JOptionPane.showMessageDialog(this, "Dados alterados com sucesso!!!");
                    objGrupoInsumo.carregaTabela(jTableGInsumo);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao alterar dados!!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nome de Grupo Insumo já existente favor mudar!!!");
            }
        }
    }//GEN-LAST:event_AlterarActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed

        int Codigo;

        if (jTableGInsumo.getSelectedRow() != -1) {
            Nome1 = jTableGInsumo.getValueAt(jTableGInsumo.getSelectedRow(), 0).toString();
            objGrupoInsumo.Pesquisar(Nome1);
            Nome.setText(objGrupoInsumo.getNome());
            Sigla.setText(objGrupoInsumo.getSigla());

        } else {
            JOptionPane.showMessageDialog(this, "Favor selecionar uma linha!!!");
        }
    }//GEN-LAST:event_PesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogGrupoInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogGrupoInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogGrupoInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogGrupoInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogGrupoInsumo dialog = new JDialogGrupoInsumo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField BuscarNome;
    private javax.swing.JButton Excluir;
    private javax.swing.JTextField Nome;
    private javax.swing.JButton Novo;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JTextField Sigla;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGInsumo;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
}
