/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Utilitarios.ConectaBD;
import gestordeobras.ClsEstoqueSaida;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Gustavo
 */
public class JDialogEstoqueSaida extends javax.swing.JDialog {

    private ClsEstoqueSaida objEstoque;
    private String NomeI;
    private String NomeGI;
    private Date data = null;
    private String DataI;
    private String DataF;
    private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    private java.util.Date dataUtil = new java.util.Date();
    private java.sql.Date dataSqlI;
    private java.sql.Date dataSqlF;
    
    /**
     * Creates new form JDialogEstoqueSaida
     */
    public JDialogEstoqueSaida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        objEstoque = new ClsEstoqueSaida();
        objEstoque.carregaTabela(jTableEstoqueSaida);
        
        jComboBoxInsumo.addItem("Todos");
        
        Connection c = ConectaBD.getconexao();
        String ConsultaSQL = "";
        ConsultaSQL = "SELECT Nome FROM insumo";
        ResultSet rs;
        
        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();
            
            
            while(rs.next()) {// se quisesse mais de uma colocar um while
                
                jComboBoxInsumo.addItem(rs.getString("Nome"));
                
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }
        
        jComboBoxGI.addItem("Todos");
        
        ConsultaSQL = "SELECT Nome FROM grupoinsumo";
        
        
        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();
            
            
            while(rs.next()) {// se quisesse mais de uma colocar um while
                
                jComboBoxGI.addItem(rs.getString("Nome"));
                
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }
        
        jComboBoxGI.setEnabled(false);
        jComboBoxInsumo.setEnabled(false);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcaoBuscar = new javax.swing.ButtonGroup();
        jComboBoxGI = new javax.swing.JComboBox<>();
        jRadioButtonData = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonTudo = new javax.swing.JRadioButton();
        DataInicio = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        DataFim = new javax.swing.JFormattedTextField();
        jRadioButtonInsumo = new javax.swing.JRadioButton();
        jRadioButtonGI = new javax.swing.JRadioButton();
        Buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstoqueSaida = new javax.swing.JTable();
        Voltar = new javax.swing.JButton();
        GerarPDF = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxInsumo = new javax.swing.JComboBox<>();
        jRadioButtonIData = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonGIData = new javax.swing.JRadioButton();
        jRadioButtonGIeI = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque Saída");

        OpcaoBuscar.add(jRadioButtonData);
        jRadioButtonData.setText("Data e agrupado");
        jRadioButtonData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonDataMouseClicked(evt);
            }
        });

        jLabel4.setText("Data Início:");

        OpcaoBuscar.add(jRadioButtonTudo);
        jRadioButtonTudo.setSelected(true);
        jRadioButtonTudo.setText("Exibir Tudo");
        jRadioButtonTudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonTudoMouseClicked(evt);
            }
        });

        try {
            DataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Data Fim:");

        try {
            DataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        OpcaoBuscar.add(jRadioButtonInsumo);
        jRadioButtonInsumo.setText("Insumo");
        jRadioButtonInsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonInsumoMouseClicked(evt);
            }
        });

        OpcaoBuscar.add(jRadioButtonGI);
        jRadioButtonGI.setText("Grupo Insumo");
        jRadioButtonGI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonGIMouseClicked(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Opções");

        jTableEstoqueSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Insumo", "Grupo Insumo", "Data Saida", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEstoqueSaida);

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        GerarPDF.setText("GerarPDF");
        GerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarPDFActionPerformed(evt);
            }
        });

        jLabel2.setText("Insumo");

        OpcaoBuscar.add(jRadioButtonIData);
        jRadioButtonIData.setText("Insumo e Data");
        jRadioButtonIData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonIDataMouseClicked(evt);
            }
        });

        jLabel3.setText("Grupo Insumo");

        OpcaoBuscar.add(jRadioButtonGIData);
        jRadioButtonGIData.setText("Grupo Insumo e Data");
        jRadioButtonGIData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonGIDataMouseClicked(evt);
            }
        });

        OpcaoBuscar.add(jRadioButtonGIeI);
        jRadioButtonGIeI.setText("Grupo de Insumo e Insumo");
        jRadioButtonGIeI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGIeIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonTudo)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonInsumo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonGI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonGIeI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonIData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonGIData)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonData)))
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Buscar)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxGI, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GerarPDF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Voltar)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxGI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(DataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButtonTudo)
                    .addComponent(jRadioButtonInsumo)
                    .addComponent(jRadioButtonGI)
                    .addComponent(jRadioButtonGIeI)
                    .addComponent(jRadioButtonIData)
                    .addComponent(jRadioButtonGIData)
                    .addComponent(jRadioButtonData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GerarPDF)
                    .addComponent(Voltar))
                .addGap(23, 23, 23))
        );

        setSize(new java.awt.Dimension(994, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonDataMouseClicked
        jComboBoxGI.setEnabled(false);
        jComboBoxInsumo.setEnabled(false);
        DataFim.setEnabled(true);
        DataInicio.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonDataMouseClicked

    private void jRadioButtonTudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonTudoMouseClicked
        jComboBoxGI.setEnabled(false);
        jComboBoxInsumo.setEnabled(false);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
        objEstoque.carregaTabela(jTableEstoqueSaida);
    }//GEN-LAST:event_jRadioButtonTudoMouseClicked

    private void jRadioButtonInsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonInsumoMouseClicked
        jComboBoxGI.setEnabled(false);
        jComboBoxInsumo.setEnabled(true);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonInsumoMouseClicked

    private void jRadioButtonGIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonGIMouseClicked
        jComboBoxGI.setEnabled(true);
        jComboBoxInsumo.setEnabled(false);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonGIMouseClicked

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        NomeGI = (String) jComboBoxGI.getSelectedItem();
        NomeI = (String) jComboBoxInsumo.getSelectedItem();

        DataI = new String(DataInicio.getText());
        DataF = new String(DataFim.getText());
        if(DataI.equals("  /  /    ")){

        }else{

            format.setLenient(false);
            try {
                data = format.parse(DataI);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            dataSqlI = new java.sql.Date(dataUtil.getTime());
        }

        if(DataF.equals("  /  /    ")){

        }else{
            format.setLenient(false);
            try {
                data = format.parse(DataF);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            dataSqlF = new java.sql.Date(dataUtil.getTime());
        }

        if(jRadioButtonInsumo.isSelected()){
            if(NomeI.equals("Todos")){
                objEstoque.carregaTabela(jTableEstoqueSaida);
            }else{
                objEstoque.carregaBuscaI(jTableEstoqueSaida, NomeI);
            }
        }

        if(jRadioButtonGI.isSelected()){
            if(NomeGI.equals("Todos")){
                objEstoque.carregaTabela(jTableEstoqueSaida);
            }else{
                objEstoque.carregaBuscaGI(jTableEstoqueSaida, NomeGI);
            }
        }

        if(jRadioButtonGIeI.isSelected()){
            if(NomeGI.equals("Todos") && NomeI.equals("Todos")){
                objEstoque.carregaTabela(jTableEstoqueSaida);
            }else if(NomeGI.equals("Todos") && !"Todos".equals(NomeI)){
                objEstoque.carregaBuscaI(jTableEstoqueSaida, NomeI);
                
            }else if(NomeI.equals("Todos") && !"Todos".equals(NomeGI)){
                objEstoque.carregaBuscaGI(jTableEstoqueSaida, NomeGI);
                
            }else if(!"Todos".equals(NomeI) && !"Todos".equals(NomeGI)){
                objEstoque.carregaBuscaGIeI(jTableEstoqueSaida, NomeGI, NomeI);
            }
        }
        
        if(jRadioButtonIData.isSelected()){
            if(NomeI.equals("Todos")){
                objEstoque.carregaBuscaData(jTableEstoqueSaida, dataSqlI, dataSqlF);
            }else{
                objEstoque.carregaBuscaIData(jTableEstoqueSaida, NomeI, dataSqlI, dataSqlF);
            }
        }

        if(jRadioButtonGIData.isSelected()){
            if(NomeGI.equals("Todos")){
                objEstoque.carregaBuscaData(jTableEstoqueSaida, dataSqlI, dataSqlF);
            }else{
                objEstoque.carregaBuscaGIData(jTableEstoqueSaida, NomeGI, dataSqlI, dataSqlF);
            }
        }
        //Eugênio: por data e agrupado por insumo (somando as quantidades)
        if(jRadioButtonData.isSelected()){
            if(DataInicio.equals("  /  /    ")){
                JOptionPane.showMessageDialog(this, "Informe a Data Inicio!!!");
            }
            else if(DataFim.equals("  /  /    ")){
                JOptionPane.showMessageDialog(this, "Informe a Data Fim!!!");
            }else {
                objEstoque.carregaBuscaData(jTableEstoqueSaida, dataSqlI, dataSqlF);
            }
        }

    }//GEN-LAST:event_BuscarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void GerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarPDFActionPerformed
        MessageFormat header = new MessageFormat("UFMG-MOC(SAÍDA):");
        MessageFormat footer = new MessageFormat("Pagina{0,number,integer}");

        try {
            jTableEstoqueSaida.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            System.err.format("Erro ao gerar pdf!!!", e.getMessage());
        }
    }//GEN-LAST:event_GerarPDFActionPerformed

    private void jRadioButtonIDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonIDataMouseClicked
        jComboBoxGI.setEnabled(false);
        jComboBoxInsumo.setEnabled(true);
        DataFim.setEnabled(true);
        DataInicio.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonIDataMouseClicked

    private void jRadioButtonGIDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonGIDataMouseClicked
        jComboBoxGI.setEnabled(true);
        jComboBoxInsumo.setEnabled(false);
        DataFim.setEnabled(true);
        DataInicio.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonGIDataMouseClicked

    private void jRadioButtonGIeIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGIeIActionPerformed
        jComboBoxGI.setEnabled(true);
        jComboBoxInsumo.setEnabled(true);
        DataFim.setEnabled(false);
        DataInicio.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonGIeIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoqueSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoqueSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoqueSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoqueSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogEstoqueSaida dialog = new JDialogEstoqueSaida(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JFormattedTextField DataFim;
    private javax.swing.JFormattedTextField DataInicio;
    private javax.swing.JButton GerarPDF;
    private javax.swing.ButtonGroup OpcaoBuscar;
    private javax.swing.JButton Voltar;
    private javax.swing.JComboBox<String> jComboBoxGI;
    private javax.swing.JComboBox<String> jComboBoxInsumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButtonData;
    private javax.swing.JRadioButton jRadioButtonGI;
    private javax.swing.JRadioButton jRadioButtonGIData;
    private javax.swing.JRadioButton jRadioButtonGIeI;
    private javax.swing.JRadioButton jRadioButtonIData;
    private javax.swing.JRadioButton jRadioButtonInsumo;
    private javax.swing.JRadioButton jRadioButtonTudo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstoqueSaida;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
}
