/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import gestordeobras.ClsCliente;
import gestordeobras.ClsEndereco;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class JDialogCadCliente extends javax.swing.JDialog {

    private ClsEndereco objEndereco;
    private ClsCliente objCliente;
    private String NomeJDialog;
    private int codEnd;
    private Date data = null;
    private String dataTexto;
    private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    private java.util.Date dataUtil = new java.util.Date();
    /**
     * Creates new form JDialogCadCliente
     */
    public JDialogCadCliente(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        objEndereco = new ClsEndereco();
        objCliente = new ClsCliente();
        
        
        
        Alterar.setEnabled(false);
        
    }
    
     public void JDialogCadCliente(String Nome1) {
        NomeJDialog = Nome1;
        
        Salvar.setEnabled(false);
        SalvarVoltar.setEnabled(false);
        Alterar.setEnabled(true);
        Nome.setEnabled(false);
        DataNasc.setEnabled(false);
        CPFCNPJ.setEnabled(false);
        RG.setEnabled(false);
        PessoaFisica.setEnabled(false);
        PessoaJuridica.setEnabled(false);
        
        
        
        
        if(NomeJDialog != null){
            
            objCliente.Pesquisar(NomeJDialog);
            
            
            codEnd = objCliente.getCod_End();
            
            objEndereco.Pesquisar(codEnd);
            
            DataNasc.setText(format.format(objCliente.getDataNasc()));
            
            Nome.setText(objCliente.getNome());
            
            CPFCNPJ.setText(objCliente.getCNPJ());
            Telefone.setText(objCliente.getTelefone());
            Celular.setText(objCliente.getCelular());
            Email.setText(objCliente.getEmail());
            RG.setText(objCliente.getRG());
            if(objCliente.getTipo() == 1){
                PessoaFisica.setSelected(true);
                PessoaJuridica.setSelected(false);
            }else{
                PessoaJuridica.setSelected(true);
                PessoaFisica.setSelected(false);
            }
            
            Rua.setText(objEndereco.getRua());
            Numero.setText(objEndereco.getNumero());
            Bairro.setText(objEndereco.getBairro());
            Cidade.setText(objEndereco.getCidade());
            Estado.setText(objEndereco.getEstado());
            CEP.setText(objEndereco.getCEP());
                       
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tipo = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        Numero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PessoaFisica = new javax.swing.JRadioButton();
        Bairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        PessoaJuridica = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Estado = new javax.swing.JTextField();
        Cidade = new javax.swing.JTextField();
        CPFCNPJ = new javax.swing.JTextField();
        Telefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Celular = new javax.swing.JTextField();
        RG = new javax.swing.JTextField();
        Salvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        SalvarVoltar = new javax.swing.JButton();
        DataNasc = new javax.swing.JFormattedTextField();
        Voltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Alterar = new javax.swing.JButton();
        CEP = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        Rua = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Cliente");

        jLabel8.setText("Número *");

        Numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KEY(evt);
            }
        });

        jLabel9.setText("Telefone *");

        jLabel1.setText("Tipo *");

        jLabel10.setText("Celular");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Endereço");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Dados Básicos");

        jLabel14.setText("Bairro *");

        Tipo.add(PessoaFisica);
        PessoaFisica.setSelected(true);
        PessoaFisica.setText("Pessoa Física");
        PessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PessoaFisicaActionPerformed(evt);
            }
        });

        Bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BairroActionPerformed(evt);
            }
        });

        jLabel11.setText("Email");

        Tipo.add(PessoaJuridica);
        PessoaJuridica.setText("Pessoa Jurídica");
        PessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PessoaJuridicaActionPerformed(evt);
            }
        });

        jLabel15.setText("Estado *");

        jLabel3.setText("CPF/CNPJ *");

        jLabel2.setText("Nome *");

        jLabel16.setText("Cidade *");

        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });

        Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidadeActionPerformed(evt);
            }
        });

        CPFCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFCNPJActionPerformed(evt);
            }
        });

        Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefoneActionPerformed(evt);
            }
        });
        Telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefoneKeyTyped(evt);
            }
        });

        jLabel4.setText("RG");

        Celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CelularKeyTyped(evt);
            }
        });

        RG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGActionPerformed(evt);
            }
        });

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        jLabel5.setText("Data Nascimento");

        SalvarVoltar.setText("Salvar e Voltar");
        SalvarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarVoltarActionPerformed(evt);
            }
        });

        try {
            DataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DataNasc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataNascActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        jLabel6.setText("CEP *");

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        try {
            CEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEPActionPerformed(evt);
            }
        });

        jLabel7.setText("Rua *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(Rua, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel13)
                                .addComponent(CEP))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PessoaFisica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PessoaJuridica))
                            .addComponent(jLabel1)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RG, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(DataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Cidade)
                                .addComponent(Estado, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Celular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(Telefone, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SalvarVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Voltar)))
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PessoaFisica)
                    .addComponent(PessoaJuridica)
                    .addComponent(DataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15))
                        .addGap(5, 5, 5)
                        .addComponent(Rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar)
                    .addComponent(SalvarVoltar)
                    .addComponent(Voltar)
                    .addComponent(Alterar))
                .addGap(20, 20, 20))
        );

        setSize(new java.awt.Dimension(569, 477));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PessoaFisicaActionPerformed

    }//GEN-LAST:event_PessoaFisicaActionPerformed

    private void BairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroActionPerformed

    private void PessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PessoaJuridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PessoaJuridicaActionPerformed

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoActionPerformed

    private void CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidadeActionPerformed

    private void CPFCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFCNPJActionPerformed

    private void TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefoneActionPerformed

    private void RGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RGActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        String opcao = Tipo.getSelection().getActionCommand();

        if(Rua.getText().equals("") || Bairro.getText().equals("") || Numero.getText().equals("")
            || Cidade.getText().equals("") || Estado.getText().equals("") || CEP.getText().equals("") ||
            Nome.getText().equals("") || CPFCNPJ.getText().equals("") || Telefone.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Campo com * são obrigatorios!!!");

        }else{

            if(DataNasc.getText().equals("  /  /    ")){
                dataTexto = "01/01/2000";

                format.setLenient(false);
                try {
                    data = format.parse(dataTexto);
                } catch (ParseException ex) {
                    ex.printStackTrace();
                }

                dataUtil = data;

                java.sql.Date dataSql = new java.sql.Date(dataUtil.getTime());

                objCliente.setDataNasc(dataSql);
            }else{
                String dataTexto = new String(DataNasc.getText());

                format.setLenient(false);
                try {
                    data = format.parse(dataTexto);
                } catch (ParseException ex) {
                    ex.printStackTrace();
                }

                dataUtil = data;

                java.sql.Date dataSql = new java.sql.Date(dataUtil.getTime());

                objCliente.setDataNasc(dataSql);
            }

            objEndereco.setRua(Rua.getText());
            objEndereco.setNumero(Numero.getText());
            objEndereco.setBairro(Bairro.getText());
            objEndereco.setCidade(Cidade.getText());
            objEndereco.setEstado(Estado.getText());
            objEndereco.setCEP(CEP.getText());
            objCliente.setNome(Nome.getText());
            objCliente.setCNPJ(CPFCNPJ.getText());
            objCliente.setTelefone(Telefone.getText());
            if("PessoaFisica".equals(opcao)){
                objCliente.setTipo(1);// pessoa fisica
            }else{
                objCliente.setTipo(2);// pessoa jurida
            }
            objCliente.setCelular(Celular.getText());

            objCliente.setEmail(Email.getText());
            objCliente.setRG(RG.getText());

            if(objCliente.PesquisarNome(Nome.getText()) == -1){
                if(objEndereco.Salvar()){
                    JOptionPane.showMessageDialog(this,"Dados gravados com sucesso!!!");
                }
                else{
                    JOptionPane.showMessageDialog(this,"Erro ao salvar dados!!!");
                }

                objCliente.setCod_End(objEndereco.PesquisaridEndereco());

                if(objCliente.Salvar()){
                    Rua.setText("");
                    Bairro.setText("");
                    Numero.setText("");
                    Cidade.setText("");
                    Estado.setText("");
                    CEP.setText("");
                    Nome.setText("");
                    Telefone.setText("");
                    Celular.setText("");
                    Email.setText("");
                    CPFCNPJ.setText("");
                    RG.setText("");
                    DataNasc.setText("");
                }
                else{
                }

            }else{
                JOptionPane.showMessageDialog(this,"Nome de Fornecedor já existente favor mudar!!!");
            }
        }

    }//GEN-LAST:event_SalvarActionPerformed

    private void SalvarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarVoltarActionPerformed
        String opcao = Tipo.getSelection().getActionCommand();

        if(Rua.getText().equals("") || Bairro.getText().equals("") || Numero.getText().equals("")
            || Cidade.getText().equals("") || Estado.getText().equals("") || CEP.getText().equals("") ||
            Nome.getText().equals("") || CPFCNPJ.getText().equals("") || Telefone.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Campo com * são obrigatorios!!!");

        }else{
            objEndereco.setRua(Rua.getText());
            objEndereco.setNumero(Numero.getText());
            objEndereco.setBairro(Bairro.getText());
            objEndereco.setCidade(Cidade.getText());
            objEndereco.setEstado(Estado.getText());
            objEndereco.setCEP(CEP.getText());
            objCliente.setNome(Nome.getText());
            objCliente.setCNPJ(CPFCNPJ.getText());
            objCliente.setTelefone(Telefone.getText());
            if("PessoaFisica".equals(opcao)){
                objCliente.setTipo(1);// pessoa fisica
            }else{
                objCliente.setTipo(2);// pessoa jurida
            }
            objCliente.setCelular(Celular.getText());

            if(DataNasc.getText().equals("  /  /    ")){
                dataTexto = "01/01/2000";

                format.setLenient(false);
                try {
                    data = format.parse(dataTexto);
                } catch (ParseException ex) {
                    ex.printStackTrace();
                }

                dataUtil = data;

                java.sql.Date dataSql = new java.sql.Date(dataUtil.getTime());

                objCliente.setDataNasc(dataSql);
            }else{
                String dataTexto = new String(DataNasc.getText());

                format.setLenient(false);
                try {
                    data = format.parse(dataTexto);
                } catch (ParseException ex) {
                    ex.printStackTrace();
                }

                dataUtil = data;

                java.sql.Date dataSql = new java.sql.Date(dataUtil.getTime());

                objCliente.setDataNasc(dataSql);
            }

            objCliente.setEmail(Email.getText());
            objCliente.setRG(RG.getText());

            if(objCliente.PesquisarNome(Nome.getText()) == -1){
                if(objEndereco.Salvar()){
                    JOptionPane.showMessageDialog(this,"Dados gravados com sucesso!!!");
                }
                else{
                    JOptionPane.showMessageDialog(this,"Erro ao salvar dados!!!");
                }

                objCliente.setCod_End(objEndereco.PesquisaridEndereco());

                if(objCliente.Salvar()){
                    dispose();
                }
                else{
                }
            }else {
                JOptionPane.showMessageDialog(this,"Nome de Fornecedor já existente favor mudar!!!");
            }
        }
    }//GEN-LAST:event_SalvarVoltarActionPerformed

    private void DataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataNascActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        if(Rua.getText().equals("") || Bairro.getText().equals("") || Numero.getText().equals("")
            || Cidade.getText().equals("") || Estado.getText().equals("") || CEP.getText().equals("") ||
            Telefone.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Campo com * são obrigatorios!!!");

        }else{
            objEndereco.setRua(Rua.getText());
            objEndereco.setNumero(Numero.getText());
            objEndereco.setBairro(Bairro.getText());
            objEndereco.setCidade(Cidade.getText());
            objEndereco.setEstado(Estado.getText());
            objEndereco.setCEP(CEP.getText());
            objCliente.setTelefone(Telefone.getText());
            objCliente.setCelular(Celular.getText());
            objCliente.setEmail(Email.getText());

            if(objEndereco.Alterar(codEnd)){
                JOptionPane.showMessageDialog(this,"Alterados com sucesso!!!");
            }
            else{
                JOptionPane.showMessageDialog(this,"Erro ao alterar dados!!!");
            }

            if(objCliente.Alterar(NomeJDialog)){
                dispose();
            }
            else{
            }
        }
    }//GEN-LAST:event_AlterarActionPerformed

    private void CEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEPActionPerformed

    private void KEY(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KEY
       String caracteres="0987654321";// lista de caracters que não devem ser aceitos
if(!caracteres.contains(evt.getKeyChar()+"")){// se o caracter que gerou o evento estiver não estiver na lista
evt.consume();//aciona esse propriedade para eliminar a ação do evento
} 

    }//GEN-LAST:event_KEY

    private void TelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefoneKeyTyped
String caracteres="0987654321";// lista de caracters que não devem ser aceitos
if(!caracteres.contains(evt.getKeyChar()+"")){// se o caracter que gerou o evento estiver não estiver na lista
evt.consume();//aciona esse propriedade para eliminar a ação do evento





}  // TODO add your handling code here:
    }//GEN-LAST:event_TelefoneKeyTyped

    private void CelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelularKeyTyped
      String caracteres="0987654321";// lista de caracters que não devem ser aceitos
if(!caracteres.contains(evt.getKeyChar()+"")){// se o caracter que gerou o evento estiver não estiver na lista
evt.consume();//aciona esse propriedade para eliminar a ação do evento





}
        



// TODO add your handling code here:
    }//GEN-LAST:event_CelularKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCadCliente dialog = new JDialogCadCliente(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JTextField Bairro;
    private javax.swing.JFormattedTextField CEP;
    private javax.swing.JTextField CPFCNPJ;
    private javax.swing.JTextField Celular;
    private javax.swing.JTextField Cidade;
    private javax.swing.JFormattedTextField DataNasc;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Estado;
    private javax.swing.JTextField Nome;
    private javax.swing.JTextField Numero;
    private javax.swing.JRadioButton PessoaFisica;
    private javax.swing.JRadioButton PessoaJuridica;
    private javax.swing.JTextField RG;
    private javax.swing.JTextField Rua;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton SalvarVoltar;
    private javax.swing.JTextField Telefone;
    private javax.swing.ButtonGroup Tipo;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
}
