/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Utilitarios.ConectaBD;
import gestordeobras.ClsCliente;
import gestordeobras.ClsEndereco;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class JDialogCliente extends javax.swing.JDialog {

    private ClsEndereco objEndereco;
    private ClsCliente objCliente;
    
    private String Nome;
    /**
     * Creates new form JDialogCliente
     */
    public JDialogCliente(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        objEndereco = new ClsEndereco();
        objCliente = new ClsCliente();
        objCliente.carregaTabela(jTableFornecedores);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Novo = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFornecedores = new javax.swing.JTable();
        BuscarNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente");

        Novo.setText("Novo");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        jTableFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome/Razão Social", "Telefone", "Celular", "Email", "Cidade", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableFornecedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Voltar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Novo)
                    .addComponent(Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Excluir)
                    .addComponent(Voltar)
                    .addComponent(Alterar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(715, 332));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        JDialogCadCliente frmDialog2 = new JDialogCadCliente(new javax.swing.JDialog(), true);
        frmDialog2.setVisible(true);
        objCliente.carregaTabela(jTableFornecedores);
    }//GEN-LAST:event_NovoActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        objCliente.carregaTabelaBusca(jTableFornecedores, BuscarNome.getText());
    }//GEN-LAST:event_BuscarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed

         int CodEndereco, CodObra, CodCliente, CodRDOGrupo, CodRDOGeral;

        if (jTableFornecedores.getSelectedRow() != -1) {
            Nome = jTableFornecedores.getValueAt(jTableFornecedores.getSelectedRow(), 0).toString();
            CodEndereco = objCliente.PesquisaridEndereco(Nome);
            CodCliente = objCliente.PesquisaridCliente(Nome);
            CodObra = objCliente.PesquisaridObra(CodCliente);
            if (objCliente.Excluir(Nome)) {
                objEndereco.Excluir(CodEndereco);
                objCliente.carregaTabela(jTableFornecedores);
            } else {
                int opcao = JOptionPane.showConfirmDialog(null, Nome + " possui informações associadas a ele! Deseja"
                        + " apagar tudo?\nEsta operação não podera ser desfeita!", "Excluir Cliente", JOptionPane.YES_NO_OPTION);

                if (opcao == 0) {

                    Connection c = ConectaBD.getconexao();

                    String ConsultaSQL = "";
                    ConsultaSQL = "SELECT r.idRDOObra, r.obra_idobra, c.idCliente FROM rdoobra r,obra o, cliente c"
                            + " WHERE r.obra_idobra = o.idobra and o.Cliente_idCliente = c.idCliente"
                            + " and c.idCliente = ? ";
                    ResultSet rs;
                    try {
                        PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
                        Query1.setInt(1, CodCliente);
                        rs = Query1.executeQuery();
                        while(rs.next()){// se quisesse mais de uma colocar um while
                            if(rs.getInt("c.idCliente") == CodCliente){
                                
                                objCliente.ExcluirMaodeObraRDO(rs.getInt("r.idRDOObra"));
                                
                                
                            }

                        }
                    } catch (java.sql.SQLException e) {
                        System.out.println(e.getMessage());

                    }

                    ConsultaSQL = "SELECT r.idRDOObra, r.obra_idobra, c.idCliente FROM rdoobragrupo r, obra o, cliente c "
                            + "WHERE r.obra_idobra = o.idobra and o.Cliente_idCliente = c.idCliente"
                            + " and c.idCliente = ? ";
                    try {
                        PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
                        Query1.setInt(1, CodCliente);
                        rs = Query1.executeQuery();
                        while(rs.next()){// se quisesse mais de uma colocar um while
                            if(rs.getInt("c.idCliente") == CodCliente){
                                
                                objCliente.ExcluirFuncionariosRDO(rs.getInt("r.idRDOObra"));
                                
                                
                            }

                        }
                    } catch (java.sql.SQLException e) {
                        System.out.println(e.getMessage());

                    }
                    
                    ConsultaSQL = "SELECT idobra, Cliente_idCliente FROM obra WHERE Cliente_idCliente = ?";
                    try {
                        PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
                        Query1.setInt(1, CodCliente);
                        rs = Query1.executeQuery();
                        while(rs.next()){// se quisesse mais de uma colocar um while
                            if(rs.getInt("Cliente_idCliente") == CodCliente){
                                
                                objCliente.ExcluirRDOObra(rs.getInt("idobra"));
                                objCliente.ExcluirRDOGrupo(rs.getInt("idobra"));    
                                
                                
                                
                            }

                        }
                    } catch (java.sql.SQLException e) {
                        System.out.println(e.getMessage());

                    }
                    
                    objCliente.ExcluirObra(CodCliente);
                    objCliente.Excluir(Nome);
                    objEndereco.Excluir(CodEndereco);
                    objCliente.carregaTabela(jTableFornecedores);

                }else{
                    System.out.println("Maluco oq q houve");
                }                    
            }

        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha!!!");
        }

    }//GEN-LAST:event_ExcluirActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed

        if(jTableFornecedores.getSelectedRow() != -1){
            this.Nome = jTableFornecedores.getValueAt(jTableFornecedores.getSelectedRow(), 0).toString();

            JDialogCadCliente frmDialog2 = new JDialogCadCliente(new javax.swing.JDialog(), true);
            frmDialog2.JDialogCadCliente(Nome);
            frmDialog2.setVisible(true);
            objCliente.carregaTabela(jTableFornecedores);

        }else{
            JOptionPane.showMessageDialog(this,"Selecione uma linha!!!");
        }
    }//GEN-LAST:event_AlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCliente dialog = new JDialogCliente(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField BuscarNome;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Novo;
    private javax.swing.JButton Voltar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFornecedores;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
}
