/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Utilitarios.ConectaBD;
import gestordeobras.ClsObra;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class JDialogCadObra extends javax.swing.JDialog {

    private ClsObra objObra;
    private String NomeJDialog;
    private int codEnd;
    private Date data = null;
    private String dataTexto;
    private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    private java.util.Date dataUtil = new java.util.Date();
    
    /**
     * Creates new form JDialogCadObra
     */
    public JDialogCadObra(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        objObra = new ClsObra();
        
        Alterar.setEnabled(false);
        
        Connection c = ConectaBD.getconexao();
        String ConsultaSQL = "";
        ConsultaSQL = "SELECT Nome FROM Cliente";
        ResultSet rs;
        ArrayList<String> list = new ArrayList<String>();
        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();
            
            
            while(rs.next()) {// se quisesse mais de uma colocar um while
                
                jComboBoxCliente.addItem(rs.getString("Nome"));
                
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }
        
    }

    public void Alterar(String NomeJ){
        NomeJDialog = NomeJ;
        
        Alterar.setEnabled(true);
        Nome.setEnabled(false);
        DataInicio.setEnabled(false);
        DataTermino.setEnabled(false);
        jComboBoxCliente.setEnabled(false);
        Salvar.setEnabled(false);
        SalvarVoltar.setEnabled(false);
        
         if(NomeJDialog != null){
            
            objObra.Pesquisar(NomeJDialog);
            
            
            
            DataInicio.setText(objObra.getDataInicio());
            DataTermino.setText(objObra.getDataTermino());
            
            Nome.setText(objObra.getNome());
            
            jComboBoxCliente.addItem(objObra.getCliente());
            Descricao.setText(objObra.getDescricao());                       
            
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DataInicio = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        DataTermino = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descricao = new javax.swing.JTextPane();
        Salvar = new javax.swing.JButton();
        SalvarVoltar = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jComboBoxCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Obra");

        jLabel1.setText("Nome *");

        jLabel2.setText("Cliente *");

        jLabel3.setText("Data Início *");

        try {
            DataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Data Término *");

        try {
            DataTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Descrição *");

        jScrollPane1.setViewportView(Descricao);

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        SalvarVoltar.setText("Salvar e Voltar");
        SalvarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarVoltarActionPerformed(evt);
            }
        });

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(DataInicio)
                                    .addComponent(DataTermino, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SalvarVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Voltar))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar)
                    .addComponent(SalvarVoltar)
                    .addComponent(Alterar)
                    .addComponent(Voltar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(346, 346));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        if(Descricao.getText().equals("") || DataInicio.getText().equals("  /  /    ") 
                || DataTermino.getText().equals("  /  /    ") || Nome.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Campo com * são obrigatorios!!!");

        }else{
            
            int codC;
            
            
            objObra.setDescricao(Descricao.getText());
            
            objObra.setNome(Nome.getText());
            
            dataTexto = new String(DataInicio.getText());
            
            format.setLenient(false);
            try {
                data = format.parse(dataTexto);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            java.sql.Date dataSqlI = new java.sql.Date(dataUtil.getTime());

            objObra.setDataI(dataSqlI);

            dataTexto = new String(DataTermino.getText());

            format.setLenient(false);
            try {
                data = format.parse(dataTexto);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            java.sql.Date dataSqlF = new java.sql.Date(dataUtil.getTime());

            objObra.setDataF(dataSqlF);
            
            codC = objObra.PesquisaridCliente((String) jComboBoxCliente.getSelectedItem());
            objObra.setCodCliente(codC);
            
            if(objObra.PesquisarNome(Nome.getText()) == -1){
                if(objObra.Salvar()){
                    
                    
                    
                    
                    
                    JOptionPane.showMessageDialog(this, "Dados gravados com sucesso!!!");
                    
                    
                    
                }else{
                    
                }
            }else{
                JOptionPane.showMessageDialog(this,"Nome de obra já existente favor mudar!!!");
            }
            
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void SalvarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarVoltarActionPerformed
        if(Descricao.getText().equals("") || DataInicio.getText().equals("  /  /    ") 
                || DataTermino.getText().equals("  /  /    ") || Nome.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Campo com * são obrigatorios!!!");

        }else{
            
            int codC;
            
            objObra.setDescricao(Descricao.getText());
            
            objObra.setNome(Nome.getText());
            
            dataTexto = new String(DataInicio.getText());
            
            format.setLenient(false);
            try {
                data = format.parse(dataTexto);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            java.sql.Date dataSqlI = new java.sql.Date(dataUtil.getTime());

            objObra.setDataI(dataSqlI);

            dataTexto = new String(DataTermino.getText());

            format.setLenient(false);
            try {
                data = format.parse(dataTexto);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            java.sql.Date dataSqlF = new java.sql.Date(dataUtil.getTime());

            objObra.setDataF(dataSqlF);
            
            codC = objObra.PesquisaridCliente((String) jComboBoxCliente.getSelectedItem());
            objObra.setCodCliente(codC);
            
            if(objObra.PesquisarNome(Nome.getText()) == -1){
                if(objObra.Salvar()){
                    JOptionPane.showMessageDialog(this, "Dados gravados com sucesso!!!");
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao gravar dados!!!");
                }
            }else{
                JOptionPane.showMessageDialog(this,"Nome de obra já existente favor mudar!!!");
            }
            
        }
    }//GEN-LAST:event_SalvarVoltarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        objObra.setDescricao(Descricao.getText());
        if(objObra.Alterar(NomeJDialog)){
                    JOptionPane.showMessageDialog(this,"Alterados com sucesso!!!");
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Erro ao alterar dados!!!");
                }
        
    }//GEN-LAST:event_AlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCadObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCadObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCadObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCadObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCadObra dialog = new JDialogCadObra(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JFormattedTextField DataInicio;
    private javax.swing.JFormattedTextField DataTermino;
    private javax.swing.JTextPane Descricao;
    private javax.swing.JTextField Nome;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton SalvarVoltar;
    private javax.swing.JButton Voltar;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
}
