/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import Utilitarios.ConectaBD;
import gestordeobras.ClsInsumo;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class JDialogCadInsumo extends javax.swing.JDialog {
    
    private ClsInsumo objInsumo;
    private String NomeJDialog;
    private JDialogInsumo objJDialogInsumo;
    /** Creates new form JDialogCadInsumo */
    public JDialogCadInsumo(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        objInsumo = new ClsInsumo();
        objJDialogInsumo = new JDialogInsumo(this, true);
        Alterar.setEnabled(false);
        //(objInsumo.carregaComboBox(GrupoInsumo));
        Connection c = ConectaBD.getconexao();
        String ConsultaSQL = "";
        ConsultaSQL = "SELECT Nome FROM grupoinsumo";
        ResultSet rs;
        ArrayList<String> list = new ArrayList<String>();
        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();
            
            
            while(rs.next()) {// se quisesse mais de uma colocar um while
                
                GrupoInsumo.addItem(rs.getString("Nome"));
                
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }
        
    }

    
    public void Alterar (String NomeJ){
        NomeJDialog = NomeJ;
        
        String NomeGP, Critico1;
        int Critico2;
        
        Salvar.setEnabled(false);
        SalvarVoltar.setEnabled(false);
        Alterar.setEnabled(true);
        Nome.setEnabled(false);
        GrupoInsumo.setEnabled(false);
        
        objInsumo.Pesquisar(NomeJ);
        Nome.setText(objInsumo.getNome());
        
        GrupoInsumo.addItem(objInsumo.PesquisarNomeGrupoInsumo(objInsumo.getCodGrupoInsumo()));
        
        Critico2 = objInsumo.getCritico();
        
        Critico1 = Integer.toString(Critico2);
        
        
        Unidade.setText(objInsumo.getUnidade());
        Critico.setText(Critico1);
        Descricao.setText(objInsumo.getDescricao());
        
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Unidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descricao = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        Critico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        GrupoInsumo = new javax.swing.JComboBox<>();
        Salvar = new javax.swing.JButton();
        SalvarVoltar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Alterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Insumo");

        jLabel1.setText("Nome *");

        jLabel3.setText("Unidade *");

        Unidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnidadeActionPerformed(evt);
            }
        });

        jLabel4.setText("Descrição *");

        Descricao.setColumns(20);
        Descricao.setRows(5);
        jScrollPane1.setViewportView(Descricao);

        jLabel5.setText("Crítico *");

        Critico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CriticoKeyTyped(evt);
            }
        });

        jLabel6.setText("Grupo de Insumo");

        GrupoInsumo.setMaximumRowCount(10);

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        SalvarVoltar.setText("Salvar e Voltar");
        SalvarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarVoltarActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        jLabel8.setText("valor inteiro ex: 200");

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SalvarVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alterar)
                        .addGap(48, 48, 48)
                        .addComponent(Voltar))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GrupoInsumo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Unidade, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Critico, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrupoInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Critico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar)
                    .addComponent(SalvarVoltar)
                    .addComponent(Voltar)
                    .addComponent(Alterar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(409, 311));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarVoltarActionPerformed
        if(Nome.getText().equals("") || Unidade.getText().equals("") ||
                Critico.getText().equals("") || Descricao.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Campos com * são obrigatorios!!!");
        }else{
            double Quantidade1;
            int Critico1, idGrupoInsumo; 
            String NomeGI;
            
            NomeGI = (String) GrupoInsumo.getSelectedItem();
            
            idGrupoInsumo = objInsumo.PesquisaridGrupoInsumo(NomeGI);
            
            objInsumo.setCodGrupoInsumo(idGrupoInsumo);
            
            objInsumo.setNome(Nome.getText());
            objInsumo.setUnidade(Unidade.getText());
            Critico1 = Integer.parseInt(Critico.getText());
            
            objInsumo.setCritico(Critico1);
            
            objInsumo.setDescricao(Descricao.getText());
            
            if(objInsumo.PesquisarNome(Nome.getText()) == -1){
                
                if(objInsumo.Salvar()){
                    JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!!!");
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao salvar dados!!!");
                }
                
            }else{
                JOptionPane.showMessageDialog(this, "Nome Insumo já existente favor colocar novo!!!");
            }
            
        }
    }//GEN-LAST:event_SalvarVoltarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
         if(Nome.getText().equals("") || Unidade.getText().equals("") ||
                Critico.getText().equals("") || Descricao.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Campos com * são obrigatorios!!!");
        }else{
            double Quantidade1;
            int Critico1, idGrupoInsumo; 
            String NomeGI;
            
            NomeGI = (String) GrupoInsumo.getSelectedItem();
            
            idGrupoInsumo = objInsumo.PesquisaridGrupoInsumo(NomeGI);
            
            objInsumo.setCodGrupoInsumo(idGrupoInsumo);
            
            objInsumo.setNome(Nome.getText());
            objInsumo.setUnidade(Unidade.getText());
            
            Critico1 = Integer.parseInt(Critico.getText());
            
            objInsumo.setCritico(Critico1);
            
            objInsumo.setDescricao(Descricao.getText());
            
            if(objInsumo.PesquisarNome(Nome.getText()) == -1){
                
                if(objInsumo.Salvar()){
                    JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!!!");
                    Nome.setText("");
                    Unidade.setText("");
                    
                    Critico.setText("");
                    Descricao.setText("");
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao salvar dados!!!");
                }
                
            }else{
                JOptionPane.showMessageDialog(this, "Nome Insumo já existente favor colocar novo!!!");
            }
            
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void UnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnidadeActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        if(Unidade.getText().equals("") ||
                Critico.getText().equals("") || Descricao.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Campos com * são obrigatorios!!!");
        }else{
           
            int Critico1;
            
            objInsumo.setUnidade(Unidade.getText());
            objInsumo.setDescricao(Descricao.getText());
            Critico1 = Integer.parseInt(Critico.getText());
            
            objInsumo.setCritico(Critico1);
                
            if(objInsumo.Altera(NomeJDialog)){
                JOptionPane.showMessageDialog(this, "Alterados com sucesso!!!");
                dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao alterar dados!!!");
            }
 
        }
    }//GEN-LAST:event_AlterarActionPerformed

    private void CriticoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CriticoKeyTyped
String caracteres="0987654321";// lista de caracters que não devem ser aceitos
if(!caracteres.contains(evt.getKeyChar()+"")){// se o caracter que gerou o evento estiver não estiver na lista
evt.consume();//aciona esse propriedade para eliminar a ação do evento





}


        // TODO add your handling code here:
    }//GEN-LAST:event_CriticoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCadInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCadInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCadInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCadInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCadInsumo dialog = new JDialogCadInsumo(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JTextField Critico;
    private javax.swing.JTextArea Descricao;
    private javax.swing.JComboBox<Object> GrupoInsumo;
    private javax.swing.JTextField Nome;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton SalvarVoltar;
    private javax.swing.JTextField Unidade;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }

}
