/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import gestordeobras.ClsEmpresa;
import gestordeobras.ClsEndereco;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class JDialogCadEmpresa extends javax.swing.JDialog {

    private ClsEmpresa objEmpresa;
    private ClsEndereco objEndereco;
    private JDialogEmpresa objDialogEmpresa;
    private String NomeJDialog;
    private int CodEnd;
    /**
     * Creates new form JDialogCadEmpresa
     */
    public JDialogCadEmpresa(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIcon();
        objEmpresa = new ClsEmpresa();
        objEndereco = new ClsEndereco();
        objDialogEmpresa = new JDialogEmpresa(this, true);
        
        Alterar.setEnabled(false);
        
    }

    public void Alterar(String Nome1){
        
        NomeJDialog = Nome1;
        
        Salvar.setEnabled(false);
        SalvarVoltar.setEnabled(false);
        Alterar.setEnabled(true);
        
        Nome.setEnabled(false);
        CNPJ.setEnabled(false);
        
        objEmpresa.Pesquisar(Nome1);
        
        CodEnd = objEmpresa.getCodEndereco();
        
        objEndereco.Pesquisar(CodEnd);
        
        Nome.setText(objEmpresa.getNome());
        CNPJ.setText(objEmpresa.getCNPJ());
        Telefone.setText(objEmpresa.getTelefone());
        Celular.setText(objEmpresa.getCelular());
        Email.setText(objEmpresa.getEmail());
        
        Rua.setText(objEndereco.getRua());
        Numero.setText(objEndereco.getNumero());
        Bairro.setText(objEndereco.getBairro());
        Cidade.setText(objEndereco.getCidade());
        Estado.setText(objEndereco.getEstado());
        CEP.setText(objEndereco.getCEP());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CNPJ = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        Telefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Celular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Rua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Numero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Bairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Cidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Estado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Salvar = new javax.swing.JButton();
        SalvarVoltar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        CEP = new javax.swing.JFormattedTextField();
        Alterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Empresa");

        jLabel1.setText("Nome *");

        jLabel2.setText("CNPJ *");

        try {
            CNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNPJActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefone *");

        Telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefoneKeyTyped(evt);
            }
        });

        jLabel4.setText("Celular");

        Celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CelularKeyTyped(evt);
            }
        });

        jLabel5.setText("Email");

        jLabel6.setText("Rua *");

        Rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuaActionPerformed(evt);
            }
        });

        jLabel7.setText("Numero *");

        Numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumeroKeyTyped(evt);
            }
        });

        jLabel8.setText("Bairro *");

        jLabel9.setText("Cidade *");

        jLabel10.setText("Estado *");

        jLabel11.setText("CEP *");

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        SalvarVoltar.setText("Salvar e Voltar");
        SalvarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarVoltarActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        try {
            CEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(Nome)
                            .addComponent(jLabel2)
                            .addComponent(CNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(Celular, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(Telefone)
                            .addComponent(jLabel5)
                            .addComponent(Email))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CEP)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(Rua, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(Bairro)
                            .addComponent(jLabel9)
                            .addComponent(Cidade)
                            .addComponent(jLabel10)
                            .addComponent(Estado))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SalvarVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Voltar)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar)
                    .addComponent(SalvarVoltar)
                    .addComponent(Voltar)
                    .addComponent(Alterar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(445, 387));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RuaActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
       
        if(Rua.getText().equals("") || Bairro.getText().equals("") || Numero.getText().equals("") 
                || Cidade.getText().equals("") || Estado.getText().equals("") || CEP.getText().equals("") ||
                Nome.getText().equals("") || CNPJ.getText().equals("") || Telefone.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Campo com asterisco (*) são obrigatorios!!!");
        }else{
            objEndereco.setRua(Rua.getText());
            objEndereco.setNumero(Numero.getText());
            objEndereco.setBairro(Bairro.getText());
            objEndereco.setCidade(Cidade.getText());
            objEndereco.setEstado(Estado.getText());
            objEndereco.setCEP(CEP.getText());
            objEmpresa.setNome(Nome.getText());
            objEmpresa.setCNPJ(CNPJ.getText());
            objEmpresa.setTelefone(Telefone.getText());
            objEmpresa.setEmail(Email.getText());
            objEmpresa.setCelular(Celular.getText());
            
            if(objEmpresa.PesquisarNome(Nome.getText()) == -1 ){
                if(objEndereco.Salvar()){
                    JOptionPane.showMessageDialog(this,"Dados gravados com sucesso!!!");
                }
                else{
                    JOptionPane.showMessageDialog(this,"Erro ao salvar dados!!!");
                }

                objEmpresa.setCodEndereco(objEndereco.PesquisaridEndereco());

                if(objEmpresa.Salvar()){
                    Salvar.setEnabled(false);
                    SalvarVoltar.setEnabled(false);
                }else{

                }
            }else{
                JOptionPane.showMessageDialog(this,"Nome de Empresa já existente favor mudar!!!");
            }
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void SalvarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarVoltarActionPerformed
        if(Rua.getText().equals("") || Bairro.getText().equals("") || Numero.getText().equals("") 
                || Cidade.getText().equals("") || Estado.getText().equals("") || CEP.getText().equals("") ||
                Nome.getText().equals("") || CNPJ.getText().equals("") || Telefone.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Campo com * são obrigatorios!!!");
        }else{
            objEndereco.setRua(Rua.getText());
            objEndereco.setNumero(Numero.getText());
            objEndereco.setBairro(Bairro.getText());
            objEndereco.setCidade(Cidade.getText());
            objEndereco.setEstado(Estado.getText());
            objEndereco.setCEP(CEP.getText());
            objEmpresa.setNome(Nome.getText());
            objEmpresa.setCNPJ(CNPJ.getText());
            objEmpresa.setTelefone(Telefone.getText());
            objEmpresa.setEmail(Email.getText());
            objEmpresa.setCelular(Celular.getText());
            
            if(objEndereco.Salvar()){
                JOptionPane.showMessageDialog(this,"Dados gravados com sucesso!!!");
            }
            else{
                JOptionPane.showMessageDialog(this,"Erro ao salvar dados!!!");
            }

            objEmpresa.setCodEndereco(objEndereco.PesquisaridEndereco());
            
            if(objEmpresa.Salvar()){
                dispose();
            }else{
                
            }
        }
            
    }//GEN-LAST:event_SalvarVoltarActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        if(Rua.getText().equals("") || Bairro.getText().equals("") || Numero.getText().equals("") 
                || Cidade.getText().equals("") || Estado.getText().equals("") || CEP.getText().equals("") ||
                 Telefone.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Campo com * são obrigatorios!!!");
            
        }else{
            objEndereco.setRua(Rua.getText());
            objEndereco.setNumero(Numero.getText());
            objEndereco.setBairro(Bairro.getText());
            objEndereco.setCidade(Cidade.getText());
            objEndereco.setEstado(Estado.getText());
            objEndereco.setCEP(CEP.getText());
            objEmpresa.setTelefone(Telefone.getText());
            objEmpresa.setCelular(Celular.getText());
            objEmpresa.setEmail(Email.getText());
            
            if(objEndereco.Alterar(CodEnd)){
                    JOptionPane.showMessageDialog(this,"Alterados com sucesso!!!");
                }
                else{
                    JOptionPane.showMessageDialog(this,"Erro ao alterar dados!!!");
                }

                if(objEmpresa.Alterar(NomeJDialog)){
                    dispose();
                }
                else{
                }
            }
    }//GEN-LAST:event_AlterarActionPerformed

    private void CNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNPJActionPerformed

    private void NumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroKeyTyped
String caracteres="0987654321";// lista de caracters que não devem ser aceitos
if(!caracteres.contains(evt.getKeyChar()+"")){// se o caracter que gerou o evento estiver não estiver na lista
evt.consume();//aciona esse propriedade para eliminar a ação do evento





}




        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroKeyTyped

    private void TelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefoneKeyTyped
String caracteres="0987654321";// lista de caracters que não devem ser aceitos
if(!caracteres.contains(evt.getKeyChar()+"")){// se o caracter que gerou o evento estiver não estiver na lista
evt.consume();//aciona esse propriedade para eliminar a ação do evento





}





        // TODO add your handling code here:
    }//GEN-LAST:event_TelefoneKeyTyped

    private void CelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelularKeyTyped
String caracteres="0987654321";// lista de caracters que não devem ser aceitos
if(!caracteres.contains(evt.getKeyChar()+"")){// se o caracter que gerou o evento estiver não estiver na lista
evt.consume();//aciona esse propriedade para eliminar a ação do evento





}


        // TODO add your handling code here:
    }//GEN-LAST:event_CelularKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCadEmpresa dialog = new JDialogCadEmpresa(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JTextField Bairro;
    private javax.swing.JFormattedTextField CEP;
    private javax.swing.JFormattedTextField CNPJ;
    private javax.swing.JTextField Celular;
    private javax.swing.JTextField Cidade;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Estado;
    private javax.swing.JTextField Nome;
    private javax.swing.JTextField Numero;
    private javax.swing.JTextField Rua;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton SalvarVoltar;
    private javax.swing.JTextField Telefone;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
}
