/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Utilitarios.ConectaBD;
import gestordeobras.ClsRDOGrupo;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class JDialogRDOGrupo extends javax.swing.JDialog {

    private ClsRDOGrupo objRDOGrupo;
    private Date data = null;
    private String DataI;
    private String DataF;
    private String Responsavel;
    private String Obra1;
    private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    private java.util.Date dataUtil = new java.util.Date();
    private java.sql.Date dataSqlI;
    private java.sql.Date dataSqlF;
    private String dataTexto;
    private int CodRdogeral;
    /**
     * Creates new form JDialogRDOGrupo
     */
    public JDialogRDOGrupo(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();   
        setIcon();
        objRDOGrupo = new ClsRDOGrupo();
        
        jComboBoxCliente.addItem("Todos");
        
        Connection c = ConectaBD.getconexao();
        String ConsultaSQL = "";
        ConsultaSQL = "SELECT Nome FROM Cliente";
        ResultSet rs;
        
        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();
            
            
            while(rs.next()) {// se quisesse mais de uma colocar um while
                
                jComboBoxCliente.addItem(rs.getString("Nome"));
                
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }
        
        jComboBoxObra.addItem("Todos");
        
        ConsultaSQL = "SELECT Nome FROM obra";
        
        
        try {
            PreparedStatement Query1 = c.prepareStatement(ConsultaSQL);
            rs = Query1.executeQuery();
            
            
            while(rs.next()) {// se quisesse mais de uma colocar um while
                
                jComboBoxObra.addItem(rs.getString("Nome"));
                
            }
        } catch (java.sql.SQLException e) {
            System.out.println(e.getMessage());
        }
        
        objRDOGrupo.carregaTabela(jTableRDOGrupo);
        
        jComboBoxObra.setEnabled(false);
        jComboBoxCliente.setEnabled(false);
        DataInicio.setEnabled(false);
        DataFim.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Opcao = new javax.swing.ButtonGroup();
        Voltar = new javax.swing.JButton();
        Novo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRDOGrupo = new javax.swing.JTable();
        Buscar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Cliente = new javax.swing.JRadioButton();
        Obra = new javax.swing.JRadioButton();
        Data = new javax.swing.JRadioButton();
        Tudo = new javax.swing.JRadioButton();
        DataFim = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        DataInicio = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxObra = new javax.swing.JComboBox<>();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatorio de Grupo de Obra");

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        Novo.setText("Novo");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });

        jTableRDOGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Obra", "Cliente", "Responsável", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableRDOGrupo);

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        jButton1.setText("Alterar/GerarPDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Opções");

        Opcao.add(Cliente);
        Cliente.setText("Cliente");
        Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClienteMouseClicked(evt);
            }
        });

        Opcao.add(Obra);
        Obra.setText("Obra");
        Obra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ObraMouseClicked(evt);
            }
        });

        Opcao.add(Data);
        Data.setText("Data");
        Data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataMouseClicked(evt);
            }
        });

        Opcao.add(Tudo);
        Tudo.setSelected(true);
        Tudo.setText("Tudo");
        Tudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TudoMouseClicked(evt);
            }
        });

        try {
            DataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Data Fim:");

        try {
            DataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Data Início:");

        jLabel4.setText("Cliente:");

        jLabel5.setText("Obra:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Novo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Buscar))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tudo)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Obra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Data)
                                .addGap(0, 451, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxObra, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(DataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Voltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Novo)
                    .addComponent(Buscar)
                    .addComponent(jComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(DataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Tudo)
                    .addComponent(Cliente)
                    .addComponent(Obra)
                    .addComponent(Data))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Excluir)
                    .addComponent(jButton1)
                    .addComponent(Voltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(839, 443));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        JDialogCadRDOGrupo frmDialog2 = new JDialogCadRDOGrupo(new javax.swing.JDialog(), true);
        frmDialog2.setVisible(true);
        objRDOGrupo.carregaTabela(jTableRDOGrupo);
    }//GEN-LAST:event_NovoActionPerformed

    private void ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClienteMouseClicked
        jComboBoxObra.setEnabled(false);
        jComboBoxCliente.setEnabled(true);
        DataInicio.setEnabled(false);
        DataFim.setEnabled(false);
    }//GEN-LAST:event_ClienteMouseClicked

    private void ObraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObraMouseClicked
        jComboBoxObra.setEnabled(true);
        jComboBoxCliente.setEnabled(false);
        DataInicio.setEnabled(false);
        DataFim.setEnabled(false);
    }//GEN-LAST:event_ObraMouseClicked

    private void DataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataMouseClicked
        jComboBoxObra.setEnabled(false);
        jComboBoxCliente.setEnabled(false);
        DataInicio.setEnabled(true);
        DataFim.setEnabled(true);
    }//GEN-LAST:event_DataMouseClicked

    private void TudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TudoMouseClicked
        jComboBoxObra.setEnabled(false);
        jComboBoxCliente.setEnabled(false);
        DataInicio.setEnabled(false);
        DataFim.setEnabled(false);

        objRDOGrupo.carregaTabela(jTableRDOGrupo);

    }//GEN-LAST:event_TudoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Obra,Cliente,Responsavel,Data;
        
        if(jTableRDOGrupo.getSelectedRow() != -1){
            Obra = jTableRDOGrupo.getValueAt(jTableRDOGrupo.getSelectedRow(), 0).toString();
            Cliente = jTableRDOGrupo.getValueAt(jTableRDOGrupo.getSelectedRow(), 1).toString();
            Responsavel = jTableRDOGrupo.getValueAt(jTableRDOGrupo.getSelectedRow(), 2).toString();
            Data = jTableRDOGrupo.getValueAt(jTableRDOGrupo.getSelectedRow(), 3).toString();
        
            JDialogCadRDOGrupo frmDialog2 = new JDialogCadRDOGrupo(new javax.swing.JDialog(), true);
            frmDialog2.Alterar(Obra, Cliente, Responsavel, Data);
            frmDialog2.setVisible(true);
            objRDOGrupo.carregaTabela(jTableRDOGrupo);
            
        }else{
            JOptionPane.showMessageDialog(this, "Favor selecionar uma linha!!!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if(Tudo.isSelected()){
            objRDOGrupo.carregaTabela(jTableRDOGrupo);
        }
        
        if(Cliente.isSelected()){
            if(jComboBoxCliente.getSelectedItem() == "Todos"){
                objRDOGrupo.carregaTabela(jTableRDOGrupo);
            }else{
                objRDOGrupo.CarregaCliente(jTableRDOGrupo,(String) jComboBoxCliente.getSelectedItem());
            }
        }
        
        if(Obra.isSelected()){
            if(jComboBoxObra.getSelectedItem() == "Todos"){
                objRDOGrupo.carregaTabela(jTableRDOGrupo);
            }else{
                objRDOGrupo.CarregaObra(jTableRDOGrupo,(String) jComboBoxObra.getSelectedItem());
            }
        }
        
        DataI = new String(DataInicio.getText());
        DataF = new String(DataFim.getText());
        
        if(Data.isSelected()){
            if(DataInicio.equals("  /  /    ")){
                JOptionPane.showMessageDialog(this, "Informe a Data Inicio!!!");
            }
            else if(DataFim.equals("  /  /    ")){
                JOptionPane.showMessageDialog(this, "Informe a Data Fim!!!");
            }else {
        
            format.setLenient(false);
            try {
                data = format.parse(DataI);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            dataSqlI = new java.sql.Date(dataUtil.getTime());
        
            format.setLenient(false);
            try {
                data = format.parse(DataF);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            dataSqlF = new java.sql.Date(dataUtil.getTime()); 
            
            objRDOGrupo.CarregaData(jTableRDOGrupo,dataSqlI, dataSqlF);
            
        }
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        dataTexto = jTableRDOGrupo.getValueAt(jTableRDOGrupo.getSelectedRow(), 3).toString();

        format.setLenient(false);
        try {
            data = format.parse(dataTexto);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

        dataUtil = data;

        java.sql.Date dataSql = new java.sql.Date(dataUtil.getTime());

        Obra1 = jTableRDOGrupo.getValueAt(jTableRDOGrupo.getSelectedRow(), 0).toString();
        Responsavel = jTableRDOGrupo.getValueAt(jTableRDOGrupo.getSelectedRow(), 2).toString();
        
        CodRdogeral = objRDOGrupo.PesquisaidRdogeral(Responsavel, Obra1, dataSql);
        
        objRDOGrupo.setCodObra(CodRdogeral);
        
        objRDOGrupo.setCodigo(CodRdogeral);
        
        if(objRDOGrupo.ExcluirFuncionarios()){
            if(objRDOGrupo.Excluir()){
                objRDOGrupo.carregaTabela(jTableRDOGrupo);
            }else{
                
            }
            
        }else{
            
        }
        
        
    }//GEN-LAST:event_ExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogRDOGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogRDOGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogRDOGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogRDOGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogRDOGrupo dialog = new JDialogRDOGrupo(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JRadioButton Cliente;
    private javax.swing.JRadioButton Data;
    private javax.swing.JFormattedTextField DataFim;
    private javax.swing.JFormattedTextField DataInicio;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Novo;
    private javax.swing.JRadioButton Obra;
    private javax.swing.ButtonGroup Opcao;
    private javax.swing.JRadioButton Tudo;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxObra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRDOGrupo;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
}
