/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Utilitarios.ConectaBD;
import Utilitarios.ControleAcesso;
import gestordeobras.ClsInsumo;
import gestordeobras.ClsPedidoCompras;
import java.awt.Dialog;
import java.awt.Toolkit;
import java.sql.Connection;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/*import javafx.application.Platform.exit;*/


/**
 *
 * @author Gustavo
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private ClsInsumo objInsumo;
    private ClsPedidoCompras objPedidoCompras;
    private Date data = null;
    private String dataTexto;
    private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    private java.util.Date dataUtil = new java.util.Date();

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        setIcon();
        objInsumo = new ClsInsumo();
        objPedidoCompras = new ClsPedidoCompras();
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }

    JFramePrincipal(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInsumo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAtrasados = new javax.swing.JTable();
        ConfEntrega = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Funcionario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Fornecedor = new javax.swing.JMenuItem();
        Insumo = new javax.swing.JMenuItem();
        GrupoInsumo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        RelatorioEntrada = new javax.swing.JMenuItem();
        RelatorioSaida = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        PedidoCompras = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        Obras = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenuItem();
        Obra = new javax.swing.JMenuItem();
        RDOGeral = new javax.swing.JMenuItem();
        RDOGrupo = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTOR DE OBRAS UFMG 1.0.3");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("Produtos Criticos");

        jTableInsumo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableInsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Insumo", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableInsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableInsumoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableInsumo);

        jLabel2.setText("Pedido de Compras ");

        jTableAtrasados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fornecedor", "Data de entrega", "Insumo", "Quantidade Pedida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableAtrasados);

        ConfEntrega.setText("Confirmar Entrega");
        ConfEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfEntregaActionPerformed(evt);
            }
        });

        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        jButton2.setText("PDF - Crítico");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Funcionario.setText("Cadastro");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Funcionário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Funcionario.add(jMenuItem1);

        Fornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Fornecedor.setText("Fornecedor");
        Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FornecedorActionPerformed(evt);
            }
        });
        Funcionario.add(Fornecedor);

        Insumo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Insumo.setText("Insumo");
        Insumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsumoActionPerformed(evt);
            }
        });
        Funcionario.add(Insumo);

        GrupoInsumo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        GrupoInsumo.setText("Grupo Insumo");
        GrupoInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrupoInsumoActionPerformed(evt);
            }
        });
        Funcionario.add(GrupoInsumo);

        jMenuBar1.add(Funcionario);

        jMenu3.setText("Controle de Estoque");

        jMenuItem3.setText("Estoque Atual");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem9.setText("Relatório Pedido Compras");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        RelatorioEntrada.setText("Relatório Entrada");
        RelatorioEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioEntradaActionPerformed(evt);
            }
        });
        jMenu3.add(RelatorioEntrada);

        RelatorioSaida.setText("Relatório Saída");
        RelatorioSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioSaidaActionPerformed(evt);
            }
        });
        jMenu3.add(RelatorioSaida);

        jMenuItem4.setText("Movimento de estoque");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        PedidoCompras.setText("Pedido de Compras");
        PedidoCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoComprasActionPerformed(evt);
            }
        });
        jMenu3.add(PedidoCompras);

        jRadioButtonMenuItem1.setText("Movimentação");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu3);

        Obras.setText("Obras");

        Cliente.setText("Cliente");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        Obras.add(Cliente);

        Obra.setText("Obra");
        Obra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObraActionPerformed(evt);
            }
        });
        Obras.add(Obra);

        RDOGeral.setText("RDO Geral");
        RDOGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDOGeralActionPerformed(evt);
            }
        });
        Obras.add(RDOGeral);

        RDOGrupo.setText("RDO por Grupo");
        RDOGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDOGrupoActionPerformed(evt);
            }
        });
        Obras.add(RDOGrupo);

        jMenuBar1.add(Obras);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ConfEntrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(Atualizar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfEntrega)
                    .addComponent(Atualizar)
                    .addComponent(Excluir))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(486, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDialogFuncionarios frmDialog2 = new JDialogFuncionarios(new javax.swing.JDialog(), true);
        frmDialog2.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FornecedorActionPerformed
        JDialogFornecedores Dialog1 = new JDialogFornecedores(new javax.swing.JDialog(), true);
        Dialog1.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_FornecedorActionPerformed

    private void GrupoInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrupoInsumoActionPerformed
        JDialogGrupoInsumo Dialog1 = new JDialogGrupoInsumo(new javax.swing.JFrame(), true);
        Dialog1.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_GrupoInsumoActionPerformed

    private void InsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsumoActionPerformed
        JDialogInsumo Dialog1 = new JDialogInsumo(new javax.swing.JDialog(), true);
        Dialog1.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_InsumoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JDialogEstoqueAtual Dialog1 = new JDialogEstoqueAtual(new javax.swing.JFrame(), true);
        Dialog1.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JDialogMovEstoque Dialog1 = new JDialogMovEstoque(new javax.swing.JDialog(), true);
        Dialog1.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void ConfEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfEntregaActionPerformed
        String NomeF, NomeI, DataE;
        int CodF, CodI;
        Double Qtd, Total;

        if (jTableAtrasados.getSelectedRow() != -1) {
            NomeF = jTableAtrasados.getValueAt(jTableAtrasados.getSelectedRow(), 0).toString();
            DataE = jTableAtrasados.getValueAt(jTableAtrasados.getSelectedRow(), 1).toString();
            NomeI = jTableAtrasados.getValueAt(jTableAtrasados.getSelectedRow(), 2).toString();
            Qtd = Double.parseDouble(jTableAtrasados.getValueAt(jTableAtrasados.getSelectedRow(), 3).toString());

            CodF = objPedidoCompras.PesquisaridFornecedor(NomeF);

            CodI = objPedidoCompras.PesquisaridInsumo(NomeI);

            format.setLenient(false);
            try {
                data = format.parse(DataE);

            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            java.sql.Date dataSql = new java.sql.Date(dataUtil.getTime());

            if (objPedidoCompras.Alterar(CodF, dataSql, CodI, Qtd)) {
                Total = objInsumo.PesquisarQtdInsumo(CodI);
                Total = Qtd + Total;
                objInsumo.AlteraQuantidade(CodI, Total);
            }

            objPedidoCompras.carregaTabelaInicio(jTableAtrasados);

        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha!!!");
        }
    }//GEN-LAST:event_ConfEntregaActionPerformed

    private void jTableInsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableInsumoMouseClicked

    }//GEN-LAST:event_jTableInsumoMouseClicked

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_AtualizarActionPerformed

    private void ObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObraActionPerformed
        JDialogObra Dialog1 = new JDialogObra(new javax.swing.JDialog(), true);
        Dialog1.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_ObraActionPerformed

    private void PedidoComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoComprasActionPerformed
        JDialogMovPedidoCompras frmDialog2 = new JDialogMovPedidoCompras(new javax.swing.JDialog(), true);
        frmDialog2.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_PedidoComprasActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        JDialogEstoquePedidos frmDialog2 = new JDialogEstoquePedidos(new javax.swing.JFrame(), true);
        frmDialog2.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void RelatorioEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioEntradaActionPerformed
        JDialogEstoqueEntrada frmDialog2 = new JDialogEstoqueEntrada(new javax.swing.JFrame(), true);
        frmDialog2.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_RelatorioEntradaActionPerformed

    private void RelatorioSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioSaidaActionPerformed
        JDialogEstoqueSaida frmDialog2 = new JDialogEstoqueSaida(new javax.swing.JFrame(), true);
        frmDialog2.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_RelatorioSaidaActionPerformed

    private void RDOGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDOGrupoActionPerformed

        JDialogRDOGrupo frmDialog2 = new JDialogRDOGrupo(new javax.swing.JDialog(), true);
        frmDialog2.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_RDOGrupoActionPerformed

    private void RDOGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDOGeralActionPerformed
        JDialogRDOGeralTabela frmDialog2 = new JDialogRDOGeralTabela(new javax.swing.JDialog(), true);
        frmDialog2.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_RDOGeralActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        JDialogCliente frmDialog2 = new JDialogCliente(new javax.swing.JDialog(), true);
        frmDialog2.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
    }//GEN-LAST:event_ClienteActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed

        if (jTableAtrasados.getSelectedRow() != -1) {
            int CodF = objPedidoCompras.PesquisaridFornecedor(jTableAtrasados.getValueAt(jTableAtrasados.getSelectedRow(), 0).toString());

            int CodI = objPedidoCompras.PesquisaridInsumo(jTableAtrasados.getValueAt(jTableAtrasados.getSelectedRow(), 2).toString());

            String Quantidade = jTableAtrasados.getValueAt(jTableAtrasados.getSelectedRow(), 3).toString();

            String Data = jTableAtrasados.getValueAt(jTableAtrasados.getSelectedRow(), 1).toString();

            Double Qtd;

            Qtd = Double.parseDouble(Quantidade);

            objPedidoCompras.setCodFornecedor(CodF);
            objPedidoCompras.setCodInsumo(CodI);
            objPedidoCompras.setQuantidade(Qtd);

            dataTexto = Data;

            format.setLenient(false);
            try {
                data = format.parse(dataTexto);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }

            dataUtil = data;

            java.sql.Date dataSql = new java.sql.Date(dataUtil.getTime());

            objPedidoCompras.setDataEntrega(dataSql);

            if (objPedidoCompras.Excluir()) {
                objPedidoCompras.carregaTabelaInicio(jTableAtrasados);
            } else {

            }

        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha!!!");
        }


    }//GEN-LAST:event_ExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MessageFormat header = new MessageFormat("CRITICO");

        MessageFormat footer = new MessageFormat("Pagina{0,number,integer}");

        try {
            jTableInsumo.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            System.err.format("Erro ao gerar pdf!!!", e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        JDialogEstoqueEntSaida frmDialog2 = new JDialogEstoqueEntSaida(new javax.swing.JFrame(), true);
        frmDialog2.setVisible(true);
        objInsumo.carregaTabelaCritico(jTableInsumo);
        objPedidoCompras.carregaTabelaInicio(jTableAtrasados);    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new JFramePrincipal().setVisible(true);
                JDialogLogin jdLogin = new JDialogLogin(null, true);
                jdLogin.setLocationRelativeTo(null);
                jdLogin.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JMenuItem Cliente;
    private javax.swing.JButton ConfEntrega;
    private javax.swing.JButton Excluir;
    private javax.swing.JMenuItem Fornecedor;
    private javax.swing.JMenu Funcionario;
    private javax.swing.JMenuItem GrupoInsumo;
    private javax.swing.JMenuItem Insumo;
    private javax.swing.JMenuItem Obra;
    private javax.swing.JMenu Obras;
    private javax.swing.JMenuItem PedidoCompras;
    private javax.swing.JMenuItem RDOGeral;
    private javax.swing.JMenuItem RDOGrupo;
    private javax.swing.JMenuItem RelatorioEntrada;
    private javax.swing.JMenuItem RelatorioSaida;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAtrasados;
    private javax.swing.JTable jTableInsumo;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images.png")));
    }
}
